/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    'inline-relationship': InlineRelationship;
  };
  collections: {
    users: User;
    media: Media;
    maps: Map;
    games: Game;
    mainQuests: MainQuest;
    sideQuests: SideQuest;
    zombies: Zombie;
    gobblegum: Gobblegum;
    perks: Perk;
    ammoMods: AmmoMod;
    fieldUpgrades: FieldUpgrade;
    zombieAttacks: ZombieAttack;
    weapons: Weapon;
    weaponBuilds: WeaponBuild;
    legal: Legal;
    augments: Augment;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    maps: {
      mainQuest: 'mainQuests';
      sideQuests: 'sideQuests';
      zombies: 'zombies';
    };
    games: {
      maps: 'maps';
      perks: 'perks';
      fieldUpgrades: 'fieldUpgrades';
      gobblegum: 'gobblegum';
      weapons: 'weapons';
    };
    perks: {
      augments: 'augments';
    };
    ammoMods: {
      augments: 'augments';
      zombies: 'zombies';
    };
    fieldUpgrades: {
      augments: 'augments';
    };
    zombieAttacks: {
      zombies: 'zombies';
    };
    weapons: {
      weaponBuilds: 'weaponBuilds';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    maps: MapsSelect<false> | MapsSelect<true>;
    games: GamesSelect<false> | GamesSelect<true>;
    mainQuests: MainQuestsSelect<false> | MainQuestsSelect<true>;
    sideQuests: SideQuestsSelect<false> | SideQuestsSelect<true>;
    zombies: ZombiesSelect<false> | ZombiesSelect<true>;
    gobblegum: GobblegumSelect<false> | GobblegumSelect<true>;
    perks: PerksSelect<false> | PerksSelect<true>;
    ammoMods: AmmoModsSelect<false> | AmmoModsSelect<true>;
    fieldUpgrades: FieldUpgradesSelect<false> | FieldUpgradesSelect<true>;
    zombieAttacks: ZombieAttacksSelect<false> | ZombieAttacksSelect<true>;
    weapons: WeaponsSelect<false> | WeaponsSelect<true>;
    weaponBuilds: WeaponBuildsSelect<false> | WeaponBuildsSelect<true>;
    legal: LegalSelect<false> | LegalSelect<true>;
    augments: AugmentsSelect<false> | AugmentsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inline-relationship".
 */
export interface InlineRelationship {
  relationship:
    | {
        relationTo: 'ammoMods';
        value: string | AmmoMod;
      }
    | {
        relationTo: 'fieldUpgrades';
        value: string | FieldUpgrade;
      }
    | {
        relationTo: 'augments';
        value: string | Augment;
      }
    | {
        relationTo: 'perks';
        value: string | Perk;
      }
    | {
        relationTo: 'zombies';
        value: string | Zombie;
      }
    | {
        relationTo: 'weaponBuilds';
        value: string | WeaponBuild;
      }
    | {
        relationTo: 'gobblegum';
        value: string | Gobblegum;
      };
  id?: string | null;
  blockName?: string | null;
  blockType: 'inline-relationship';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ammoMods".
 */
export interface AmmoMod {
  id: string;
  /**
   * Name of the ammo mod.
   */
  title: string;
  /**
   * Game this ammo mod belongs to.
   */
  game: string | Game;
  /**
   * Featured image of this ammo mod.
   */
  image?: (string | null) | Media;
  /**
   * Description used in tooltips and hover cards.
   */
  description: string;
  /**
   * Augments that belong to this ammo mod.
   */
  augments?: {
    docs?: (string | Augment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Zombies that are weak to this ammo mod.
   */
  zombies?: {
    docs?: (string | Zombie)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games".
 */
export interface Game {
  id: string;
  /**
   * Name of the game.
   */
  title: string;
  /**
   * Unique slug for the game. Used to form the canonical URL.
   */
  slug: string;
  /**
   * Release date of the game.
   */
  releaseDate: string;
  /**
   * Cover image of the game.
   */
  image: string | Media;
  /**
   * Maps that are featured in this game.
   */
  maps?: {
    docs?: (string | Map)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Perks that are featured in this game.
   */
  perks?: {
    docs?: (string | Perk)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Field upgrades that are featured in this game.
   */
  fieldUpgrades?: {
    docs?: (string | FieldUpgrade)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Gobblegum that are featured in this game.
   */
  gobblegum?: {
    docs?: (string | Gobblegum)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Weapons that are featured in this game.
   */
  weapons?: {
    docs?: (string | Weapon)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Title of the media.
   */
  title: string;
  /**
   * Used as the caption and alt text for the media.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maps".
 */
export interface Map {
  id: string;
  /**
   * Name of the map.
   */
  title: string;
  /**
   * Unique slug for the map. Used to form the canonical URL.
   */
  slug: string;
  /**
   * Release date of the map.
   */
  releaseDate: string;
  /**
   * Game this map belongs to.
   */
  game: string | Game;
  /**
   * Featured image of this map.
   */
  image: string | Media;
  /**
   * SEO description used in meta tags and in preview cards.
   */
  description: string;
  /**
   * Main quest that belongs to this map.
   */
  mainQuest?: {
    docs?: (string | MainQuest)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Side quests that belong to this map.
   */
  sideQuests?: {
    docs?: (string | SideQuest)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Zombies that belong to this map.
   */
  zombies?: {
    docs?: (string | Zombie)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mainQuests".
 */
export interface MainQuest {
  id: string;
  /**
   * Title of the main quest.
   */
  title: string;
  /**
   * Determines if this quest should show a 'Coming Soon' badge and have the main page not be accessible.
   */
  isComingSoon: boolean;
  /**
   * Difficulty of the main quest.
   */
  difficulty?: ('Easy' | 'Medium' | 'Hard') | null;
  /**
   * Map this main quest belongs to.
   */
  map: string | Map;
  /**
   * Contents of the main quest.
   */
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sideQuests".
 */
export interface SideQuest {
  id: string;
  /**
   * Name of the side quest.
   */
  title: string;
  /**
   * Unique slug for the side quest. Used to form the canonical URL.
   */
  slug: string;
  /**
   * Map this side quest belongs to.
   */
  map: string | Map;
  /**
   * Featured image of this side quest.
   */
  image?: (string | null) | Media;
  /**
   * SEO description used in meta tags and in preview cards.
   */
  description: string;
  /**
   * Contents of the side quest.
   */
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zombies".
 */
export interface Zombie {
  id: string;
  /**
   * Name of the zombie.
   */
  title: string;
  /**
   * Unique slug for the zombie. Used to form the canonical URL.
   */
  slug: string;
  /**
   * Determines if this zombie should show a 'Coming Soon' badge and have the main page not be accessible.
   */
  isComingSoon?: boolean | null;
  /**
   * Featured image of this zombie.
   */
  image: string | Media;
  /**
   * SEO description used in meta tags, tooltips, hover cards, and in preview cards.
   */
  description: string;
  /**
   * Games this zombie is featured in.
   */
  games: (string | Game)[];
  /**
   * Maps this zombie is featured in.
   */
  maps: (string | Map)[];
  /**
   * Type of the zombie.
   */
  type: 'Normal' | 'Special' | 'Elite' | 'Boss';
  /**
   * Speed of the zombie.
   */
  speed: 'Slow' | 'Medium' | 'Fast';
  /**
   * Weak points of the zombie.
   */
  weakPoints: string[];
  /**
   * Elemental weaknesses of the zombie.
   */
  elementalWeakness?: (string | AmmoMod)[] | null;
  /**
   * Attacks of the zombie.
   */
  attacks: (string | ZombieAttack)[];
  /**
   * Spawn behavior of the zombie.
   */
  spawnBehavior: string;
  /**
   * Combat strategy of the zombie.
   */
  combatStrategy: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zombieAttacks".
 */
export interface ZombieAttack {
  id: string;
  /**
   * Name of the zombie attack.
   */
  title: string;
  /**
   * Range of the zombie attack.
   */
  range: 'Short' | 'Medium' | 'Long';
  /**
   * Description of the zombie attack.
   */
  description: string;
  /**
   * Zombies that use this attack.
   */
  zombies?: {
    docs?: (string | Zombie)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "perks".
 */
export interface Perk {
  id: string;
  /**
   * Name of the perk.
   */
  title: string;
  /**
   * Game this perk belongs to.
   */
  game: string | Game;
  /**
   * Featured image of this perk.
   */
  image: string | Media;
  /**
   * Description used in tooltips and hover cards.
   */
  description: string;
  /**
   * Modifier used in tooltips and hover cards.
   */
  modifier?: string | null;
  /**
   * Augments that belong to this perk.
   */
  augments?: {
    docs?: (string | Augment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "augments".
 */
export interface Augment {
  id: string;
  /**
   * Name of the augment.
   */
  title: string;
  /**
   * Type of the augment.
   */
  type: 'Major' | 'Minor';
  /**
   * Featured image of this augment.
   */
  image: string | Media;
  /**
   * Description used in tooltips and hover cards.
   */
  description: string;
  /**
   * Perk this augment belongs to.
   */
  perk?: (string | null) | Perk;
  /**
   * Ammo mod this augment belongs to.
   */
  ammoMod?: (string | null) | AmmoMod;
  /**
   * Field upgrade this augment belongs to.
   */
  fieldUpgrade?: (string | null) | FieldUpgrade;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fieldUpgrades".
 */
export interface FieldUpgrade {
  id: string;
  /**
   * Name of the field upgrade.
   */
  title: string;
  /**
   * Game this field upgrade belongs to.
   */
  game: string | Game;
  /**
   * Featured image of this field upgrade.
   */
  image?: (string | null) | Media;
  /**
   * Description used in tooltips and hover cards.
   */
  description: string;
  /**
   * Augments that belong to this field upgrade.
   */
  augments?: {
    docs?: (string | Augment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gobblegum".
 */
export interface Gobblegum {
  id: string;
  /**
   * Name of the gobblegum.
   */
  title: string;
  /**
   * Rarity of the gobblegum.
   */
  rarity: 'Classic' | 'Mega' | 'Rare-Mega' | 'Ultra-Rare Mega' | 'Rare' | 'Epic' | 'Legendary' | 'Ultra';
  /**
   * Type of the gobblegum.
   */
  type: 'Round-Based' | 'Time-Based' | 'Immediate' | 'Player-Activated';
  /**
   * Game this gobblegum belongs to.
   */
  game: string | Game;
  /**
   * Featured image of this gobblegum.
   */
  image: string | Media;
  /**
   * Description used in tooltips and hover cards.
   */
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weapons".
 */
export interface Weapon {
  id: string;
  /**
   * Name of the weapon.
   */
  title: string;
  /**
   * Games this weapon is featured in.
   */
  games: (string | Game)[];
  /**
   * Featured image of this weapon.
   */
  image: string | Media;
  /**
   * Weapon builds that belong to this weapon.
   */
  weaponBuilds?: {
    docs?: (string | WeaponBuild)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weaponBuilds".
 */
export interface WeaponBuild {
  id: string;
  /**
   * Name of the weapon build.
   */
  title: string;
  /**
   * Weapon this build belongs to.
   */
  weapon: string | Weapon;
  /**
   * Attachments that belong to this weapon build.
   */
  attachments?: string[] | null;
  /**
   * Build code of the weapon build.
   */
  buildCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal".
 */
export interface Legal {
  id: string;
  /**
   * Title of the legal document.
   */
  title: string;
  /**
   * Unique slug for the legal document. Used to form the canonical URL.
   */
  slug: string;
  /**
   * Contents of the legal document.
   */
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'maps';
        value: string | Map;
      } | null)
    | ({
        relationTo: 'games';
        value: string | Game;
      } | null)
    | ({
        relationTo: 'mainQuests';
        value: string | MainQuest;
      } | null)
    | ({
        relationTo: 'sideQuests';
        value: string | SideQuest;
      } | null)
    | ({
        relationTo: 'zombies';
        value: string | Zombie;
      } | null)
    | ({
        relationTo: 'gobblegum';
        value: string | Gobblegum;
      } | null)
    | ({
        relationTo: 'perks';
        value: string | Perk;
      } | null)
    | ({
        relationTo: 'ammoMods';
        value: string | AmmoMod;
      } | null)
    | ({
        relationTo: 'fieldUpgrades';
        value: string | FieldUpgrade;
      } | null)
    | ({
        relationTo: 'zombieAttacks';
        value: string | ZombieAttack;
      } | null)
    | ({
        relationTo: 'weapons';
        value: string | Weapon;
      } | null)
    | ({
        relationTo: 'weaponBuilds';
        value: string | WeaponBuild;
      } | null)
    | ({
        relationTo: 'legal';
        value: string | Legal;
      } | null)
    | ({
        relationTo: 'augments';
        value: string | Augment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maps_select".
 */
export interface MapsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  releaseDate?: T;
  game?: T;
  image?: T;
  description?: T;
  mainQuest?: T;
  sideQuests?: T;
  zombies?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games_select".
 */
export interface GamesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  releaseDate?: T;
  image?: T;
  maps?: T;
  perks?: T;
  fieldUpgrades?: T;
  gobblegum?: T;
  weapons?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mainQuests_select".
 */
export interface MainQuestsSelect<T extends boolean = true> {
  title?: T;
  isComingSoon?: T;
  difficulty?: T;
  map?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sideQuests_select".
 */
export interface SideQuestsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  map?: T;
  image?: T;
  description?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zombies_select".
 */
export interface ZombiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  isComingSoon?: T;
  image?: T;
  description?: T;
  games?: T;
  maps?: T;
  type?: T;
  speed?: T;
  weakPoints?: T;
  elementalWeakness?: T;
  attacks?: T;
  spawnBehavior?: T;
  combatStrategy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gobblegum_select".
 */
export interface GobblegumSelect<T extends boolean = true> {
  title?: T;
  rarity?: T;
  type?: T;
  game?: T;
  image?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "perks_select".
 */
export interface PerksSelect<T extends boolean = true> {
  title?: T;
  game?: T;
  image?: T;
  description?: T;
  modifier?: T;
  augments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ammoMods_select".
 */
export interface AmmoModsSelect<T extends boolean = true> {
  title?: T;
  game?: T;
  image?: T;
  description?: T;
  augments?: T;
  zombies?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fieldUpgrades_select".
 */
export interface FieldUpgradesSelect<T extends boolean = true> {
  title?: T;
  game?: T;
  image?: T;
  description?: T;
  augments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zombieAttacks_select".
 */
export interface ZombieAttacksSelect<T extends boolean = true> {
  title?: T;
  range?: T;
  description?: T;
  zombies?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weapons_select".
 */
export interface WeaponsSelect<T extends boolean = true> {
  title?: T;
  games?: T;
  image?: T;
  weaponBuilds?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weaponBuilds_select".
 */
export interface WeaponBuildsSelect<T extends boolean = true> {
  title?: T;
  weapon?: T;
  attachments?: T;
  buildCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_select".
 */
export interface LegalSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "augments_select".
 */
export interface AugmentsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  image?: T;
  description?: T;
  perk?: T;
  ammoMod?: T;
  fieldUpgrade?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}