/** Seed env vars so `@/env` validates when tests load modules that import it. */
process.env.RESEND_API_KEY = "test-key"
process.env.RESEND_AUDIENCE_ID = "test-audience"
process.env.HASH_SALT = "test-salt"
process.env.LINEAR_API_KEY = "test-linear-key"
process.env.LINEAR_WORKSPACE = "test-workspace"
process.env.LINEAR_USER_FEEDBACK_LABEL = "test-user-feedback-label"
process.env.LINEAR_DEFAULT_ASSIGNEE_ID = "test-assignee"
process.env.VERCEL_ENV = "development"
process.env.VERCEL_URL = "[REDACTED]"
process.env.VERCEL_PROJECT_PRODUCTION_URL = "[REDACTED]"
