import type { MapConfig } from "@/data/interactive-map"
import { Option } from "effect"
import { perks, sharedMarkers, weapons } from "@/map-configs/markers"

export const config: MapConfig = {
	layers: [
		{
			id: "destroyed",
			title: "Destroyed",
			image: "/layers/paradox-junction/paradox-junction-destroyed-layer.webp",
			markers: [
				{
					id: "cul-de-sac",
					title: "Cul-de-Sac",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.5, y: 0.5 }],
				},
				{
					id: "trinity-ave",
					title: "Trinity Ave.",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.5, y: 0.759 }],
				},
				{
					id: "green-house",
					title: "Green House",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.389, y: 0.461 }],
				},
				{
					id: "green-house-backyard",
					title: "Green House Backyard",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.293, y: 0.443 }],
				},
				{
					id: "green-house-garage",
					title: "Green House Garage",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.371, y: 0.502 }],
				},
				{
					id: "yellow-house",
					title: "Yellow House",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.618, y: 0.5 }],
				},
				{
					id: "yellow-house-backyard",
					title: "Yellow House Backyard",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.717, y: 0.468 }],
				},
				{
					id: "yellow-house-garage",
					title: "Yellow House Garage",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.614, y: 0.441 }],
				},
				{
					id: "loot-cyst",
					title: "Loot Cyst",
					description: "Glowing, biological growths that provide loot when fed enough souls.",
					category: "objectives",
					icon: Option.some("/icons/objectives/loot-cyst.webp"),
					locations: [
						{ x: 0.544, y: 0.4 },
						{ x: 0.451, y: 0.402 },
						{ x: 0.38, y: 0.422 },
						{ x: 0.263, y: 0.431 },
						{ x: 0.376, y: 0.527 },
						{ x: 0.594, y: 0.471 },
						{ x: 0.656, y: 0.511 },
						{ x: 0.673, y: 0.397 },
						{ x: 0.602, y: 0.658 },
						{ x: 0.434, y: 0.703 },
						{ x: 0.584, y: 0.813 },
						{ x: 0.417, y: 0.836 },
					],
				},
				{
					...sharedMarkers["ammo-cache"],
					icon: Option.some("/icons/equipment/ammo-cache-bo7.webp"),
					locations: [
						{ x: 0.524, y: 0.528 },
						{ x: 0.733, y: 0.517 },
						{ x: 0.262, y: 0.415 },
						{ x: 0.545, y: 0.718 },
					],
				},
				{
					...sharedMarkers["armor-wall-buy"],
					locations: [
						{ x: 0.352, y: 0.518 },
						{ x: 0.664, y: 0.399 },
					],
				},
				{
					...sharedMarkers["audio-log"],
					locations: [
						{ title: "The Search Begins", x: 0.589, y: 0.485 },
						{ title: "Run Aground", x: 0.402, y: 0.487 },
						{ title: "Dead Air", x: 0.335, y: 0.464 },
						{ title: "Makin' It Right", x: 0.517, y: 0.808 },
						{ title: "Before Times", x: 0.658, y: 0.389 },
						{
							title: "Trickery",
							description:
								"Only appears after collecting the 'Storm Coming' audio log in Normal Nuketown.",
							x: 0.472,
							y: 0.661,
						},
					],
				},
				{
					...sharedMarkers["door-buy"],
					locations: [
						{ x: 0.501, y: 0.478 },
						{ x: 0.52, y: 0.473 },
						{ x: 0.502, y: 0.447 },
						{ x: 0.594, y: 0.454 },
						{ x: 0.593, y: 0.407 },
						{ x: 0.58, y: 0.513 },
						{ x: 0.604, y: 0.537 },
						{ x: 0.636, y: 0.425 },
						{ x: 0.66, y: 0.493 },
						{ x: 0.427, y: 0.471 },
						{ x: 0.391, y: 0.498 },
						{ x: 0.354, y: 0.504 },
						{ x: 0.374, y: 0.543 },
						{ x: 0.398, y: 0.416 },
						{ x: 0.349, y: 0.469 },
						{ x: 0.355, y: 0.428 },
					],
				},
				{
					...sharedMarkers["gobblegum-machine"],
					locations: [{ x: 0.435, y: 0.553 }],
				},
				{
					...sharedMarkers["mystery-box"],
					locations: [
						{ x: 0.474, y: 0.536 },
						{ x: 0.288, y: 0.501 },
						{ x: 0.742, y: 0.411 },
						{ x: 0.502, y: 0.714 },
					],
				},
				{
					...sharedMarkers["pack-a-punch"],
					locations: [{ x: 0.501, y: 0.894 }],
				},
				{
					...sharedMarkers["power-door"],
					locations: [{ x: 0.473, y: 0.624 }],
				},
				{
					...sharedMarkers["rampage-inducer"],
					locations: [{ x: 0.519, y: 0.598 }],
				},
				{
					...sharedMarkers.arsenal,
					locations: [{ x: 0.545, y: 0.56 }],
				},
				{
					...sharedMarkers.document,
					locations: [{ title: "Paper Hearts", x: 0.387, y: 0.45 }],
				},
				{
					...sharedMarkers.exfil,
					icon: Option.some("/icons/equipment/exfil-bo7.webp"),
					locations: [{ x: 0.436, y: 0.671 }],
				},
				{
					...sharedMarkers.portal,
					title: "Temporal Conduit",
					description: "Travel through time",
					locations: [{ x: 0.531, y: 0.429 }],
				},
				{
					...sharedMarkers.trap,
					title: "Electro-Shock Defenses",
					locations: [
						{ x: 0.372, y: 0.467 },
						{ x: 0.61, y: 0.461 },
					],
				},
				{
					...sharedMarkers.workbench,
					locations: [{ x: 0.513, y: 0.484 }],
				},
				{
					...perks["quick-revive"],
					locations: [{ x: 0.474, y: 0.502 }],
				},
				{
					...perks["der-wunderfizz"],
					locations: [{ x: 0.336, y: 0.738 }],
				},
				{
					...perks["random-perk"],
					locations: [
						{ x: 0.373, y: 0.476 },
						{ x: 0.238, y: 0.47 },
						{ x: 0.607, y: 0.49 },
					],
				},
				{
					...weapons["velox-5.7"],
					locations: [{ x: 0.455, y: 0.573 }],
				},
				{
					...weapons["razor-9mm"],
					locations: [{ x: 0.253, y: 0.379 }],
				},
				{
					...weapons["m10-breacher"],
					locations: [{ x: 0.754, y: 0.475 }],
				},
				{
					...weapons.m8a1,
					locations: [{ x: 0.613, y: 0.696 }],
				},
				{
					...weapons["vs-recon"],
					locations: [{ x: 0.402, y: 0.719 }],
				},
				{
					...weapons["mxr-17"],
					locations: [{ x: 0.471, y: 0.855 }],
				},
			],
		},
		{
			id: "normal",
			title: "Normal",
			image: "/layers/paradox-junction/paradox-junction-normal-layer.webp",
			markers: [
				{
					id: "cul-de-sac",
					title: "Cul-de-Sac",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.5, y: 0.492 }],
				},
				{
					id: "trinity-ave",
					title: "Trinity Ave.",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.5, y: 0.751 }],
				},
				{
					id: "green-house",
					title: "Green House",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.389, y: 0.453 }],
				},
				{
					id: "green-house-backyard",
					title: "Green House Backyard",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.293, y: 0.435 }],
				},
				{
					id: "green-house-garage",
					title: "Green House Garage",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.371, y: 0.494 }],
				},
				{
					id: "yellow-house",
					title: "Yellow House",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.618, y: 0.492 }],
				},
				{
					id: "yellow-house-backyard",
					title: "Yellow House Backyard",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.717, y: 0.46 }],
				},
				{
					id: "yellow-house-garage",
					title: "Yellow House Garage",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.614, y: 0.433 }],
				},
				{
					...sharedMarkers["aether-crystal"],
					locations: [
						{ x: 0.419, y: 0.393 },
						{ x: 0.224, y: 0.419 },
						{ x: 0.576, y: 0.378 },
						{ x: 0.588, y: 0.55 },
						{ x: 0.533, y: 0.59 },
						{ x: 0.335, y: 0.71 },
						{ x: 0.394, y: 0.853 },
						{ x: 0.553, y: 0.854 },
					],
				},
				{
					...sharedMarkers["ammo-cache"],
					icon: Option.some("/icons/equipment/ammo-cache-bo7.webp"),
					locations: [
						{ x: 0.524, y: 0.528 },
						{ x: 0.733, y: 0.517 },
						{ x: 0.262, y: 0.415 },
						{ x: 0.545, y: 0.718 },
					],
				},
				{
					...sharedMarkers["armor-wall-buy"],
					locations: [
						{ x: 0.352, y: 0.51 },
						{ x: 0.664, y: 0.391 },
					],
				},
				{
					...sharedMarkers["audio-log"],
					locations: [
						{ title: "Head Cannon", x: 0.473, y: 0.819 },
						{ title: "Live Air", x: 0.706, y: 0.44 },
						{
							title: "Storm Coming",
							description:
								"Only appears after collecting the 'Before Times' audio log in Destroyed Nuketown.",
							x: 0.234,
							y: 0.471,
						},
						{
							title: "Aftermath",
							description:
								"Only appears after collecting the 'Trickery' audio log in Destroyed Nuketown.",
							x: 0.46,
							y: 0.444,
						},
					],
				},
				{
					...sharedMarkers["door-buy"],
					locations: [
						{ x: 0.501, y: 0.47 },
						{ x: 0.52, y: 0.465 },
						{ x: 0.502, y: 0.439 },
						{ x: 0.594, y: 0.446 },
						{ x: 0.593, y: 0.399 },
						{ x: 0.58, y: 0.505 },
						{ x: 0.604, y: 0.529 },
						{ x: 0.636, y: 0.417 },
						{ x: 0.66, y: 0.485 },
						{ x: 0.427, y: 0.463 },
						{ x: 0.391, y: 0.49 },
						{ x: 0.354, y: 0.496 },
						{ x: 0.374, y: 0.535 },
						{ x: 0.398, y: 0.408 },
						{ x: 0.349, y: 0.461 },
						{ x: 0.355, y: 0.42 },
					],
				},
				{
					...sharedMarkers["gobblegum-machine"],
					locations: [{ x: 0.435, y: 0.545 }],
				},
				{
					...sharedMarkers["mystery-box"],
					locations: [
						{ x: 0.474, y: 0.528 },
						{ x: 0.288, y: 0.493 },
						{ x: 0.742, y: 0.403 },
						{ x: 0.502, y: 0.706 },
					],
				},
				{
					...sharedMarkers["pack-a-punch"],
					locations: [{ x: 0.501, y: 0.886 }],
				},
				{
					...sharedMarkers["power-door"],
					locations: [{ x: 0.473, y: 0.616 }],
				},
				{
					...sharedMarkers.arsenal,
					locations: [{ x: 0.545, y: 0.552 }],
				},
				{
					...sharedMarkers.document,
					locations: [
						{ title: "Wanted Man", x: 0.547, y: 0.634 },
						{ title: "Helpful Information", x: 0.625, y: 0.469 },
					],
				},
				{
					...sharedMarkers.exfil,
					icon: Option.some("/icons/equipment/exfil-bo7.webp"),
					locations: [{ x: 0.436, y: 0.671 }],
				},
				{
					...sharedMarkers.portal,
					title: "Temporal Conduit",
					description: "Travel through time",
					locations: [{ x: 0.531, y: 0.421 }],
				},
				{
					...sharedMarkers.trap,
					title: "Electro-Shock Defenses",
					locations: [
						{ x: 0.372, y: 0.459 },
						{ x: 0.61, y: 0.453 },
					],
				},
				{
					...sharedMarkers.workbench,
					locations: [{ x: 0.513, y: 0.476 }],
				},
				{
					...perks["random-perk"],
					locations: [
						{ x: 0.475, y: 0.494 },
						{ x: 0.389, y: 0.441 },
						{ x: 0.253, y: 0.377 },
						{ x: 0.601, y: 0.467 },
						{ x: 0.794, y: 0.496 },
						{ x: 0.335, y: 0.731 },
					],
				},
				{
					...weapons["coda-9"],
					locations: [{ x: 0.457, y: 0.563 }],
				},
				{
					...weapons["echo-12"],
					locations: [{ x: 0.755, y: 0.466 }],
				},
				{
					...weapons["dravec-45"],
					locations: [{ x: 0.24, y: 0.462 }],
				},
				{
					...weapons["xr3-ion"],
					locations: [{ x: 0.615, y: 0.684 }],
				},
				{
					...weapons["mk-78"],
					locations: [{ x: 0.405, y: 0.711 }],
				},
				{
					...weapons["carbon-57"],
					locations: [{ x: 0.471, y: 0.854 }],
				},
			],
		},
		{
			id: "boss-arena",
			title: "Boss Arena",
			image: "/layers/paradox-junction/paradox-junction-boss-arena-layer.webp",
			markers: [
				{
					id: "cul-de-sac",
					title: "Cul-de-Sac",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.5, y: 0.5 }],
				},
				{
					id: "trinity-ave",
					title: "Trinity Ave.",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.5, y: 0.759 }],
				},
				{
					id: "green-house-backyard",
					title: "Green House Backyard",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.293, y: 0.443 }],
				},
				{
					id: "yellow-house-backyard",
					title: "Yellow House Backyard",
					description: "",
					category: "general",
					type: "label",
					icon: Option.none(),
					locations: [{ x: 0.717, y: 0.468 }],
				},
				{
					...sharedMarkers["ammo-cache"],
					icon: Option.some("/icons/equipment/ammo-cache-bo7.webp"),
					locations: [
						{ x: 0.733, y: 0.517 },
						{ x: 0.262, y: 0.415 },
						{ x: 0.545, y: 0.718 },
					],
				},
			],
		},
	],
}
