import type { MapConfig } from "@/data/interactive-map"
import { Option } from "effect"
import { perks, sharedMarkers, weapons } from "@/map-configs/markers"

export const config: MapConfig = {
	layers: [
		{
			id: "main",
			title: "Main",
			image: "/layers/rex-infernus/rex-infernus-main-layer.webp",
			markers: [
				{
					id: "her-house",
					title: "Her House",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "nexus-forge",
					title: "Nexus Forge",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "nexus-core",
					title: "Nexus Core",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "caltheris-passage",
					title: "Caltheris Passage",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "caltheris-entrance",
					title: "Caltheris Entrance",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "caltheris-main-chamber",
					title: "Caltheris Main Chamber",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "caltheris-sanctuary",
					title: "Caltheris Sanctuary",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "ruina-insula",
					title: "Ruina Insula",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "dravakar-passage",
					title: "Dravakar Passage",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "dravakar-entrance",
					title: "Dravakar Entrance",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "dravakar-main-chamber",
					title: "Dravakar Main Chamber",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "dravakar-sanctuary",
					title: "Dravakar Sanctuary",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "aranea-insula",
					title: "Aranea Insula",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "veytharion-passage",
					title: "Veytharion Passage",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "veytharion-entrance",
					title: "Veytharion Entrance",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "veytharion-main-chamber",
					title: "Veytharion Main Chamber",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "veytharion-sanctuary",
					title: "Veytharion Sanctuary",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "spira-insula",
					title: "Spira Insula",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "nxyara-passage",
					title: "Nxyara Passage",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "nxyara-entrance",
					title: "Nxyara Entrance",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "nxyara-main-chamber",
					title: "Nxyara Main Chamber",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "nxyara-sanctuary",
					title: "Nxyara Sanctuary",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
				{
					id: "nxyara-inner-sanctum",
					title: "Nxyara Inner Sanctum",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [],
				},
			],
		},
	],
}
