import type { MapConfig, MapConfigMetadata } from "."
import { Option } from "effect"
import { type MapMarker, sharedMarkers } from "./markers"

export const metadata: MapConfigMetadata = {
	id: "ashes-of-the-damned",
	title: "Ashes of the Damned",
	image: "/previews/ashes-of-the-damned-preview.webp",
	state: Option.some("New"),
	game: "Black Ops 7",
	description:
		"Explore Ashes of the Damned in Black Ops 7 Zombies. Find locations for all perks, weapons, fast travels, intel, and more with our interactive map.",
}

/** All markers are shared between each map layer, the layer just changes the view of the map to adjust for height */
const layerMarkers: MapMarker[] = [
	{
		id: "janus-towers-plaza",
		title: "Janus Towers Plaza",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.494, y: 0.086 }],
	},
	{
		id: "server-room",
		title: "Server Room",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.51, y: 0.105 }],
	},
	{
		id: "monolith-forest",
		title: "Monolith Forest",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.433, y: 0.191 }],
	},
	{
		id: "collapsed-tower",
		title: "Collapsed Tower",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.628, y: 0.167 }],
	},
	{
		id: "blackwater-lake",
		title: "Blackwater Lake",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.473, y: 0.33 }],
	},
	{
		id: "cabin",
		title: "Cabin",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.451, y: 0.325 }],
	},
	{
		id: "boathouse",
		title: "Boathouse",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.447, y: 0.299 }],
	},
	{
		id: "toolshed",
		title: "Toolshed",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.433, y: 0.341 }],
	},
	{
		id: "vandorn-farm",
		title: "Vandorn Farm",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.6, y: 0.294 }],
	},
	{
		id: "barn",
		title: "Barn",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.606, y: 0.323 }],
	},
	{
		id: "farmhouse",
		title: "Farmhouse",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.576, y: 0.322 }],
	},
	{
		id: "garage",
		title: "Garage",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.571, y: 0.296 }],
	},
	{
		id: "cellar",
		title: "Cellar",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.595, y: 0.322 }],
	},
	{
		id: "lost-cabins",
		title: "Lost Cabins",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.445, y: 0.429 }],
	},
	{
		id: "grounded-ship",
		title: "Grounded Ship",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.613, y: 0.444 }],
	},
	{
		id: "ashwood",
		title: "Ashwood",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.532, y: 0.54 }],
	},
	{
		id: "ashwood-sheriffs-office",
		title: "Ashwood Sheriff's Office",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.572, y: 0.523 }],
	},
	{
		id: "judgement-square",
		title: "Judgement Square",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.573, y: 0.562 }],
	},
	{
		id: "ashwood-bridge",
		title: "Ashwood Bridge",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.535, y: 0.563 }],
	},
	{
		id: "the-ruby-rabbit",
		title: "The Ruby Rabbit",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.507, y: 0.558 }],
	},
	{
		id: "hargroves-mercentile",
		title: "Hargrove's Mercantile",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.564, y: 0.549 }],
	},
	{
		id: "tailor-shop",
		title: "Tailor Shop",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.579, y: 0.546 }],
	},
	{
		id: "rabbit-alley",
		title: "Rabbit Alley",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.489, y: 0.558 }],
	},
	{
		id: "crashed-rocket",
		title: "Crashed Rocket",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.64, y: 0.69 }],
	},
	{
		id: "orda-graveyard",
		title: "Orda Graveyard",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.438, y: 0.722 }],
	},
	{
		id: "zarya-cosmodrome",
		title: "Zarya Cosmodrome",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.641, y: 0.816 }],
	},
	{
		id: "support-systems",
		title: "Support Systems",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.628, y: 0.807 }],
	},
	{
		id: "yuris-lab",
		title: "Yuri's Lab",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.609, y: 0.837 }],
	},
	{
		id: "control-room",
		title: "Control Room",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.637, y: 0.781 }],
	},
	{
		id: "exit-115",
		title: "Exit 115",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.409, y: 0.911 }],
	},
	{
		id: "rebas-diner",
		title: "Reba's Diner",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.424, y: 0.9 }],
	},
	{
		id: "mcdougals-service-station",
		title: "McDougal's Service Station",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.409, y: 0.933 }],
	},
	{
		id: "crashed-plane",
		title: "Crashed Plane",
		type: "label",
		description: "",
		icon: null,
		category: "general",
		locations: [{ x: 0.536, y: 0.875 }],
	},
	{
		...sharedMarkers["ammo-cache"],
		locations: [
			{ x: 0.493, y: 0.107 },
			{ x: 0.459, y: 0.331 },
			{ x: 0.444, y: 0.315 },
			{ x: 0.576, y: 0.294 },
			{ x: 0.617, y: 0.327 },
			{ x: 0.536, y: 0.57 },
			{ x: 0.501, y: 0.563 },
			{ x: 0.581, y: 0.573 },
			{ x: 0.629, y: 0.796 },
			{ x: 0.666, y: 0.827 },
			{ x: 0.613, y: 0.832 },
			{ x: 0.428, y: 0.937 },
			{ x: 0.428, y: 0.886 },
		],
	},
	{
		...sharedMarkers["armor-wall-buy"],
		locations: [
			{ x: 0.45, y: 0.301 },
			{ x: 0.57, y: 0.299 },
			{ x: 0.561, y: 0.548 },
			{ x: 0.639, y: 0.777 },
			{ x: 0.406, y: 0.938 },
		],
	},
	{
		...sharedMarkers.arsenal,
		locations: [],
	},
]

export const config: MapConfig = {
	id: "ashes-of-the-damned",
	layers: [
		{
			id: "default-tac-map",
			title: "Default Tac-Map",
			image: "/layers/ashes-of-the-damned/ashes-of-the-damned-layer.webp",
			markers: layerMarkers,
		},
		{
			id: "upper-ashwood",
			title: "Upper Ashwood",
			image: "/layers/ashes-of-the-damned/ashes-of-the-damned-upper-ashwood.webp",
			markers: layerMarkers,
		},
		{
			id: "lower-zarya",
			title: "Lower Zarya",
			image: "/layers/ashes-of-the-damned/ashes-of-the-damned-lower-zarya.webp",
			markers: layerMarkers,
		},
		{
			id: "farm-cellar",
			title: "Farm Cellar",
			image: "/layers/ashes-of-the-damned/ashes-of-the-damned-farm-cellar.webp",
			markers: layerMarkers,
		},
	],
}
