import type { MapConfig } from "@/map-configs"
import { perks, sharedMarkers, weapons } from "./markers"

const citadelleDesMorts: MapConfig = {
	id: "citadelle-des-morts",
	title: "Citadelle Des Morts",
	game: "Black Ops 6",
	description:
		"Explore Citadelle Des Morts in BO6 Zombies. Find all Points of Power & Oil Traps, Fast Travels, intel, and more with our interactive map.",
	layers: [
		{
			id: "citadelle-des-morts",
			title: "Citadelle Des Morts",
			image: "/layers/citadelle-des-morts/citadelle-des-morts-layer.webp",
			markers: [
				{
					id: "town-square",
					type: "label",
					category: "general",
					title: "Town Square",
					description: "",
					icon: null,
					locations: [{ x: 0.5, y: 0.729 }],
				},
				{
					id: "tavern",
					type: "label",
					category: "general",
					title: "Tavern",
					description: "",
					icon: null,
					locations: [{ x: 0.45, y: 0.645 }],
				},
				{
					id: "tavern-cellar",
					type: "label",
					category: "general",
					title: "Tavern Cellar",
					description: "",
					icon: null,
					locations: [{ x: 0.494, y: 0.643 }],
				},
				{
					id: "nature-path",
					type: "label",
					category: "general",
					title: "Nature Path",
					description: "",
					icon: null,
					locations: [{ x: 0.35, y: 0.64 }],
				},
				{
					id: "hilltop",
					type: "label",
					category: "general",
					title: "Hilltop",
					description: "",
					icon: null,
					locations: [{ x: 0.365, y: 0.56 }],
				},
				{
					id: "village-ascent",
					type: "label",
					category: "general",
					title: "Village Ascent",
					description: "",
					icon: null,
					locations: [{ x: 0.65, y: 0.635 }],
				},
				{
					id: "upper-village",
					type: "label",
					category: "general",
					title: "Upper Village",
					description: "",
					icon: null,
					locations: [{ x: 0.65, y: 0.54 }],
				},
				{
					id: "courtyard",
					type: "label",
					category: "general",
					title: "Courtyard",
					description: "",
					icon: null,
					locations: [{ x: 0.502, y: 0.438 }],
				},
				{
					id: "hillside-ramparts",
					type: "label",
					category: "general",
					title: "Hillside Ramparts",
					description: "",
					icon: null,
					locations: [{ x: 0.4, y: 0.458 }],
				},
				{
					id: "village-ramparts",
					type: "label",
					category: "general",
					title: "Village Ramparts",
					description: "",
					icon: null,
					locations: [{ x: 0.6, y: 0.458 }],
				},
				{
					id: "entrance-hall",
					type: "label",
					category: "general",
					title: "Entrance Hall",
					description: "",
					icon: null,
					locations: [{ x: 0.5, y: 0.295 }],
				},
				{
					id: "dining-hall",
					type: "label",
					category: "general",
					title: "Dining Hall",
					description: "",
					icon: null,
					locations: [{ x: 0.56, y: 0.148 }],
				},
				{
					id: "alchemical-lab",
					type: "label",
					category: "general",
					title: "Alchemical Lab",
					description: "",
					icon: null,
					locations: [{ x: 0.485, y: 0.146 }],
				},
				{
					id: "sitting-rooms",
					type: "label",
					category: "general",
					title: "Sitting Rooms",
					description: "",
					icon: null,
					locations: [{ x: 0.412, y: 0.192 }],
				},
				{
					id: "undercroft",
					type: "label",
					category: "general",
					title: "Undercroft",
					description: "",
					icon: null,
					locations: [{ x: 0.694, y: 0.287 }],
				},
				{
					id: "dungeon",
					type: "label",
					category: "general",
					title: "Dungeon",
					description: "",
					icon: null,
					locations: [{ x: 0.885, y: 0.271 }],
				},
				{
					id: "oubilette-room",
					type: "label",
					category: "general",
					title: "Oubilette Room",
					description: "",
					icon: null,
					locations: [{ x: 0.789, y: 0.336 }],
				},
				{
					...sharedMarkers["ammo-cache"],
					locations: [
						{ x: 0.553, y: 0.724 },
						{ x: 0.332, y: 0.549 },
						{ x: 0.475, y: 0.452 },
						{ x: 0.552, y: 0.498 },
						{ x: 0.5, y: 0.265 },
						{ x: 0.527, y: 0.191 },
						{ x: 0.428, y: 0.215 },
						{ x: 0.698, y: 0.256 },
						{ x: 0.926, y: 0.283 },
						{ x: 0.755, y: 0.337 },
						{ x: 0.66, y: 0.602 },
					],
				},
				{
					...sharedMarkers["armor-wall-buy"],
					locations: [
						{ x: 0.435, y: 0.673, title: "Tier II Armor" },
						{ x: 0.485, y: 0.31, title: "Tier II Armor" },
						{ x: 0.468, y: 0.115, title: "Tier III Armor" },
						{ x: 0.801, y: 0.312, title: "Tier III Armor" },
					],
				},
				{
					...sharedMarkers.arsenal,
					locations: [
						{ x: 0.5, y: 0.631 },
						{ x: 0.53, y: 0.451 },
						{ x: 0.481, y: 0.17 },
					],
				},
				{
					...sharedMarkers["crafting-table"],
					locations: [
						{ x: 0.486, y: 0.663 },
						{ x: 0.466, y: 0.282 },
					],
				},
				{
					...sharedMarkers["door-buy"],
					locations: [
						{ x: 0.435, y: 0.718 },
						{ x: 0.564, y: 0.706 },
						{ x: 0.404, y: 0.481 },
						{ x: 0.595, y: 0.481 },
						{ x: 0.421, y: 0.376 },
						{ x: 0.579, y: 0.376 },
						{ x: 0.538, y: 0.26 },
						{ x: 0.525, y: 0.228 },
						{ x: 0.472, y: 0.228 },
						{ x: 0.45, y: 0.212 },
						{ x: 0.563, y: 0.198 },
						{ x: 0.596, y: 0.133 },
						{ x: 0.385, y: 0.149 },
						{ x: 0.664, y: 0.241 },
						{ x: 0.725, y: 0.302 },
						{ x: 0.751, y: 0.302 },
						{ x: 0.827, y: 0.359 },
						{ x: 0.856, y: 0.328 },
						{ x: 0.931, y: 0.227 },
					],
				},
				{
					...sharedMarkers.exfil,
					locations: [{ x: 0.475, y: 0.644 }],
				},
				{
					...sharedMarkers["fast-travel"],
					locations: [
						{
							x: 0.5,
							y: 0.495,
							title: "Lion Cannon",
							description: "Use to Fast Travel to the Town Square after opening the Entrance Hall.",
						},
						{
							x: 0.5,
							y: 0.354,
							title: "Entrance Hall Door",
							description: "Blow open the door using the Lion Cannon to gain access.",
						},
						{
							x: 0.787,
							y: 0.394,
							title: "Cave Slide",
							description: "Use to Fast Travel to the Tavern Cellar.",
						},
					],
				},
				{
					...sharedMarkers["gobblegum-machine"],
					locations: [
						{ x: 0.465, y: 0.701 },
						{ x: 0.532, y: 0.36 },
						{ x: 0.778, y: 0.285 },
					],
				},
				{
					...sharedMarkers["mystery-box"],
					locations: [
						{ x: 0.447, y: 0.777 },
						{ x: 0.663, y: 0.662 },
						{ x: 0.426, y: 0.566 },
						{ x: 0.534, y: 0.3 },
						{ x: 0.666, y: 0.301 },
						{ x: 0.896, y: 0.29 },
					],
				},
				{
					...sharedMarkers["pack-a-punch"],
					locations: [{ x: 0.775, y: 0.365 }],
				},
				{
					...sharedMarkers.portal,
					locations: [
						{
							x: 0.508,
							y: 0.619,
							title: "Tavern Cellar Portal",
							description: "Teleport to the Entrance Hall.",
						},
					],
				},
				{
					...sharedMarkers["rampage-inducer"],
					locations: [{ x: 0.541, y: 0.787 }],
				},
				{
					...sharedMarkers.trap,
					locations: [
						{ x: 0.347, y: 0.554, title: "Points of Power Trap" },
						{ x: 0.63, y: 0.615, title: "Points of Power Trap" },
						{ x: 0.5, y: 0.448, title: "Points of Power Trap" },
						{ x: 0.58, y: 0.481, title: "Oil Trap" },
						{ x: 0.604, y: 0.47, title: "Oil Trap" },
						{ x: 0.414, y: 0.481, title: "Oil Trap" },
						{ x: 0.402, y: 0.47, title: "Oil Trap" },
						{ x: 0.403, y: 0.183, title: "Points of Power Trap" },
						{ x: 0.788, y: 0.329, title: "Points of Power Trap" },
						{ x: 0.909, y: 0.272, title: "Points of Power Trap" },
					],
				},
				{
					...sharedMarkers["audio-log"],
					locations: [
						{ x: 0.576, y: 0.497, title: "Good Afternoon Mr. Richtofen" },
						{ x: 0.378, y: 0.412, title: "You Would've Done the Same" },
						{ x: 0.431, y: 0.666, title: "Historically Speaking" },
						{ x: 0.667, y: 0.341, title: "Get It Done" },
						{ x: 0.467, y: 0.345, title: "Do Your Damn Job" },
						{ x: 0.873, y: 0.265, title: "Fair Enough" },
						{ x: 0.695, y: 0.598, title: "Survival of the Fittest" },
						{ x: 0.323, y: 0.62, title: "The Foundling" },
						{ x: 0.417, y: 0.245, title: "New Horizons" },
						{ x: 0.533, y: 0.202, title: "The Four Bastards" },
					],
				},
				{
					...sharedMarkers.document,
					locations: [
						{
							x: 0.406,
							y: 0.579,
							title: "Family Book",
							description: "Shoot the stack of papers on the rafters in the barn.",
						},
						{
							x: 0.506,
							y: 0.658,
							title: "Some Context",
							description:
								"Use the Lion Cannon Fast Travel and spam interact when sliding on the Tavern roof to pick up the document.",
						},
						{
							x: 0.505,
							y: 0.134,
							title: "Statuesque",
							description:
								"Interact with piles of books in the Alchemical Lab until the document drops out of one of them.",
						},
						{
							x: 0.653,
							y: 0.622,
							title: "Intake Form",
							description: "Obtained from completing the Wishing Well side quest.",
						},
					],
				},
				{
					...perks["der-wunderfizz"],
					locations: [{ x: 0.42, y: 0.619 }],
				},
				{
					...perks["deadshot-daiquiri"],
					locations: [{ x: 0.378, y: 0.583 }],
				},
				{
					...perks["elemental-pop"],
					locations: [{ x: 0.377, y: 0.37 }],
				},
				{
					...perks.juggernog,
					locations: [{ x: 0.511, y: 0.31 }],
				},
				{
					...perks["melee-macchiato"],
					locations: [{ x: 0.622, y: 0.369 }],
				},
				{
					...perks["quick-revive"],
					locations: [{ x: 0.866, y: 0.244 }],
				},
				{
					...perks["speed-cola"],
					locations: [{ x: 0.646, y: 0.507 }],
				},
				{
					...perks["stamin-up"],
					locations: [{ x: 0.381, y: 0.171 }],
				},
				{
					...perks["vulture-aid"],
					locations: [{ x: 0.558, y: 0.084 }],
				},
				{
					...weapons.gs45,
					locations: [{ x: 0.513, y: 0.668 }],
				},
				{
					...weapons["kompakt-92"],
					locations: [{ x: 0.361, y: 0.603 }],
				},
				{
					...weapons.xm4,
					locations: [{ x: 0.618, y: 0.535 }],
				},
				{
					...weapons["lr-7.62"],
					locations: [{ x: 0.448, y: 0.499 }],
				},
				{
					...weapons["as-val"],
					locations: [{ x: 0.525, y: 0.406 }],
				},
				{
					...weapons["tanto.22"],
					locations: [{ x: 0.524, y: 0.144 }],
				},
				{
					...weapons["marine-sp"],
					locations: [{ x: 0.413, y: 0.225 }],
				},
				{
					...weapons["gpmg-7"],
					locations: [{ x: 0.7, y: 0.226 }],
				},
				{
					...weapons.ksv,
					locations: [{ x: 0.914, y: 0.228 }],
				},
			],
		},
	],
}

export default citadelleDesMorts
