import type { MapConfig } from "@/data/interactive-map"
import { Option } from "effect"
import { perks, sharedMarkers, weapons } from "`@/map-configs/markers`"

export const config: MapConfig = {
	layers: [
		{
			id: "main",
			title: "Main",
			image: "/layers/kowakujo/kowakujo-main-map.webp",
			markers: [
				{
					id: "outer-ward",
					title: "Outer Ward",
					category: "general",
					type: "label",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.489, y: 0.752 }],
				},
				{
					id: "staging-area",
					title: "Staging Area",
					category: "general",
					type: "label",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.465, y: 0.659 }],
				},
				{
					id: "gatehouse",
					title: "Gatehouse",
					category: "general",
					type: "label",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.544, y: 0.668 }],
				},
				{
					id: "flower-garden",
					title: "Flower Garden",
					category: "general",
					type: "label",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.674, y: 0.675 }],
				},
				{
					id: "kitchens",
					title: "Kitchens",
					category: "general",
					type: "label",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.671, y: 0.516 }],
				},
				{
					id: "central-courtyard",
					title: "Central Courtyard",
					category: "general",
					type: "label",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.482, y: 0.485 }],
				},
				{
					id: "tea-garden",
					title: "Tea Garden",
					category: "general",
					type: "label",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.365, y: 0.531 }],
				},
				{
					id: "training-area",
					title: "Training Area",
					category: "general",
					type: "label",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.264, y: 0.577 }],
				},
				{
					id: "stables",
					title: "Stables",
					category: "general",
					type: "label",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.36, y: 0.66 }],
				},
				{
					id: "tenshu-entrance",
					title: "Tenshu Entrance",
					category: "general",
					type: "label",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.472, y: 0.402 }],
				},
				{
					id: "onsen-baths",
					title: "Onsen Baths",
					category: "general",
					type: "label",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.5, y: 0.316 }],
				},
				{
					id: "war-room",
					title: "War Room",
					category: "general",
					type: "label",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.497, y: 0.25 }],
				},
				{
					id: "shoguns-sanctum",
					title: "Shogun's Sanctum",
					category: "general",
					type: "label",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.505, y: 0.216 }],
				},
				{
					id: "workshop",
					title: "Workshop",
					category: "general",
					type: "label",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.434, y: 0.23 }],
				},
				{
					id: "storage-rooms",
					title: "Storage Rooms",
					category: "general",
					type: "label",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.404, y: 0.302 }],
				},
				{
					id: "collapsed-study",
					title: "Collapsed Study",
					category: "general",
					type: "label",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.42, y: 0.368 }],
				},
				{
					id: "tenshu-rooftops",
					title: "Tenshu Rooftops",
					category: "general",
					type: "label",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.396, y: 0.26 }],
				},
				{
					...sharedMarkers["ammo-cache"],
					icon: Option.some("/icons/equipment/ammo-cache-bo7.webp"),
					locations: [
						{ x: 0.51, y: 0.753 },
						{ x: 0.513, y: 0.668 },
						{ x: 0.727, y: 0.657 },
						{ x: 0.615, y: 0.5 },
						{ x: 0.48, y: 0.467 },
						{ x: 0.312, y: 0.55 },
						{ x: 0.301, y: 0.633 },
						{ x: 0.399, y: 0.355 },
						{ x: 0.429, y: 0.307 },
						{ x: 0.474, y: 0.28 },
						{ x: 0.485, y: 0.183 },
					],
				},
				{
					...sharedMarkers["armor-wall-buy"],
					locations: [
						{ x: 0.661, y: 0.721 },
						{ x: 0.368, y: 0.574 },
						{ x: 0.455, y: 0.366 },
					],
				},
				{
					...sharedMarkers.arsenal,
					locations: [
						{ x: 0.398, y: 0.616 },
						{ x: 0.718, y: 0.455 },
						{ x: 0.412, y: 0.239 },
					],
				},
				{
					...sharedMarkers["audio-log"],
					locations: [
						{ x: 0.532, y: 0.729, title: "Two Brothers" },
						{ x: 0.724, y: 0.744, title: "Paydirt" },
						{ x: 0.286, y: 0.613, title: "Subverting Control" },
						{
							x: 0.457,
							y: 0.385,
							title: "Extra Crispy",
							description:
								"After unlocking Pack-a-Punch, underneath a pizza on the roof accessible via the Onsen Baths bridge",
						},
						{
							x: 0.423,
							y: 0.284,
							title: "What About The Cat",
							description: "Obtaining after unlocking Pack-a-Punch",
						},
						{
							x: 0.546,
							y: 0.235,
							title: "Katanas Out",
							description: "Obtainable after completing the 'The Reunion' side quest",
						},
						{
							x: 0.452,
							y: 0.232,
							title: "Takeo's Resolve",
							description: "Obtainable after the first main quest in-game cutscene",
						},
						{
							x: 0.408,
							y: 0.302,
							title: "Mitsuhime's Reverence",
							description: "Obtainable after the fox mask main quest in-game cutscene",
						},
						{
							x: 0.498,
							y: 0.805,
							title: "Takeshi's Dread",
							description: "Obtainable after the coin purse main quest in-game cutscene",
						},
						{
							x: 0.656,
							y: 0.473,
							title: "Takeo's Devotion",
							description: "Obtainable after the pestle main quest in-game cutscene",
						},
						{
							x: 0.405,
							y: 0.495,
							title: "Takeshi's Perception",
							description: "Obtainable after the Sake Cup main quest in-game cutscene",
						},
						{
							x: 0.397,
							y: 0.404,
							title: "Mitsuhime's Trepidation",
							description: "Obtainable after obtaining the Crest Mediallion from the main quest",
						},
					],
				},
				{
					...sharedMarkers.document,
					locations: [
						{
							x: 0.447,
							y: 0.231,
							title: "Hair Rising",
							description:
								"After unlocking Pack-a-Punch, melee the stack of papers on the shelf before the Tenshu Rooftops",
						},
						{
							x: 0.714,
							y: 0.532,
							title: "PssPssPss",
							description: "Interact with the barrels to obtain",
						},
					],
				},
				{
					...sharedMarkers["crafting-table"],
					locations: [
						{ x: 0.656, y: 0.687 },
						{ x: 0.296, y: 0.539 },
						{ x: 0.385, y: 0.216 },
					],
				},
				{
					...sharedMarkers["door-buy"],
					locations: [
						{ x: 0.467, y: 0.714 },
						{ x: 0.525, y: 0.709 },
						{ x: 0.601, y: 0.672 },
						{ x: 0.691, y: 0.616 },
						{ x: 0.57, y: 0.521 },
						{ x: 0.428, y: 0.499 },
						{ x: 0.291, y: 0.639 },
						{ x: 0.429, y: 0.659 },
						{ x: 0.448, y: 0.358 },
						{ x: 0.422, y: 0.277 },
						{ x: 0.451, y: 0.227 },
						{ x: 0.497, y: 0.262 },
						{ x: 0.481, y: 0.35 },
					],
				},
				{
					...sharedMarkers["power-door"],
					locations: [
						{ x: 0.5, y: 0.627 },
						{ x: 0.476, y: 0.586 },
						{ x: 0.504, y: 0.54 },
						{ x: 0.452, y: 0.436 },
						{ x: 0.448, y: 0.247 },
						{ x: 0.453, y: 0.236 },
					],
				},
				{
					...sharedMarkers.exfil,
					icon: Option.some("/icons/equipment/exfil-bo7.webp"),
					locations: [
						{ x: 0.453, y: 0.402 },
						{ x: 0.75, y: 0.72 },
						{ x: 0.413, y: 0.648 },
					],
				},
				{
					...sharedMarkers["fast-travel"],
					title: "Ninja Kite",
					locations: [
						{ x: 0.443, y: 0.242, description: "Glide to the Grounds" },
						{ x: 0.5, y: 0.664, description: "Glide to the Castle" },
					],
				},
				{
					...sharedMarkers["gobblegum-machine"],
					locations: [
						{ x: 0.497, y: 0.714 },
						{ x: 0.616, y: 0.657 },
						{ x: 0.335, y: 0.682 },
						{ x: 0.543, y: 0.463 },
						{ x: 0.419, y: 0.262 },
					],
				},
				{
					...sharedMarkers["mystery-box"],
					locations: [
						{ x: 0.45, y: 0.763 },
						{ x: 0.625, y: 0.623 },
						{ x: 0.378, y: 0.602 },
						{ x: 0.351, y: 0.533 },
						{ x: 0.634, y: 0.455 },
						{ x: 0.482, y: 0.496 },
						{ x: 0.511, y: 0.38 },
						{ x: 0.384, y: 0.32 },
						{ x: 0.429, y: 0.319 },
					],
				},
				{
					...sharedMarkers["pack-a-punch"],
					locations: [{ x: 0.542, y: 0.212 }],
				},
				{
					...sharedMarkers["rampage-inducer"],
					locations: [{ x: 0.494, y: 0.809 }],
				},
				{
					...sharedMarkers.trap,
					title: "Ghostly Rifleman",
					locations: [
						{ x: 0.516, y: 0.713 },
						{ x: 0.534, y: 0.711 },
						{ x: 0.686, y: 0.615 },
						{ x: 0.696, y: 0.618 },
						{ x: 0.31, y: 0.656 },
						{ x: 0.313, y: 0.632 },
						{ x: 0.447, y: 0.438 },
						{ x: 0.457, y: 0.436 },
					],
				},
				{
					...sharedMarkers.workbench,
					locations: [
						{ x: 0.409, y: 0.489, title: "Sake Cup Workbench" },
						{ x: 0.433, y: 0.214, title: "Maneki-Neko Workbench" },
					],
				},
				{
					...perks["death-perception"],
					locations: [{ x: 0.321, y: 0.702 }],
				},
				{
					...perks["der-wunderfizz"],
					locations: [{ x: 0.424, y: 0.403 }],
				},
				{
					...perks["double-tap"],
					locations: [{ x: 0.73, y: 0.527 }],
				},
				{
					...perks["elemental-pop"],
					locations: [{ x: 0.51, y: 0.284 }],
				},
				{
					...perks.juggernog,
					locations: [{ x: 0.501, y: 0.429 }],
				},
				{
					...perks["melee-macchiato"],
					locations: [{ x: 0.228, y: 0.534 }],
				},
				{
					...perks["mule-kick"],
					locations: [{ x: 0.452, y: 0.285 }],
				},
				{
					...perks["phd-flopper"],
					locations: [{ x: 0.391, y: 0.388 }],
				},
				{
					...perks["quick-revive"],
					locations: [{ x: 0.521, y: 0.784 }],
				},
				{
					...perks["speed-cola"],
					locations: [{ x: 0.521, y: 0.608 }],
				},
				{
					...perks["stamin-up"],
					locations: [{ x: 0.499, y: 0.646 }],
				},
				{
					...perks["vulture-aid"],
					locations: [{ x: 0.447, y: 0.213 }],
				},
				{
					...perks["wisp-tea"],
					locations: [{ x: 0.666, y: 0.754 }],
				},
				{
					...weapons["jaeger-45"],
					locations: [{ x: 0.478, y: 0.714 }],
				},
				{
					...weapons["m10-breacher"],
					locations: [{ x: 0.574, y: 0.659 }],
				},
				{
					...weapons["m34-novaline"],
					locations: [{ x: 0.689, y: 0.554 }],
				},
				{
					...weapons["peacekeeper-mk1"],
					locations: [{ x: 0.482, y: 0.431 }],
				},
				{
					...weapons["warden-308"],
					locations: [{ x: 0.254, y: 0.607 }],
				},
				{
					...weapons["mpc-25"],
					locations: [{ x: 0.34, y: 0.701 }],
				},
				{
					...weapons["xr3-ion"],
					locations: [{ x: 0.457, y: 0.246 }],
				},
				{
					...weapons["echo-12"],
					locations: [{ x: 0.461, y: 0.669 }],
				},
				{
					...weapons["ryden-45k"],
					locations: [{ x: 0.724, y: 0.63 }],
				},
				{
					...weapons.xm325,
					locations: [{ x: 0.513, y: 0.306 }],
				},
				{
					...weapons["m15-mod-0"],
					locations: [{ x: 0.455, y: 0.346 }],
				},
				{
					...weapons["mk-78"],
					locations: [{ x: 0.378, y: 0.284 }],
				},
			],
		},
	],
}
