import type { MapConfig } from "@/map-configs"

const reckoning: MapConfig = {
	id: "reckoning",
	title: "Reckoning",
	isComingSoon: true,
	game: "Black Ops 6",
	description:
		"Explore Reckoning in BO6 Zombies. Find all C.A.S.T.E.R. Turrets, Intel, and more with our interactive map.",
	image: "/layers/reckoning.webp",
	markers: [
		{
			id: "t1-mutant-research-lab",
			type: "label",
			category: "general",
			title: "T1 Mutant Research Lab",
			description: "",
			icon: null,
			locations: [],
		},
		{
			id: "t1-mutant-research-test-area",
			type: "label",
			category: "general",
			title: "T1 Mutant Research Test Area",
			description: "",
			icon: null,
			locations: [],
		},
		{
			id: "t1-project-janus-reception",
			type: "label",
			category: "general",
			title: "T1 Project Janus Reception",
			description: "",
			icon: null,
			locations: [],
		},
		{
			id: "t2-android-assembly",
			type: "label",
			category: "general",
			title: "T2 Android Assembly",
			description: "",
			icon: null,
			locations: [],
		},
		{
			id: "t2-dark-entity-containment",
			type: "label",
			category: "general",
			title: "T2 Dark Entity Containment",
			description: "",
			icon: null,
			locations: [],
		},
		{
			id: "t1-executive-suit",
			type: "label",
			category: "general",
			title: "T1 Executive Suit",
			description: "",
			icon: null,
			locations: [],
		},
		{
			id: "t1-quantum-computing-core",
			type: "label",
			category: "general",
			title: "T1 Quantum Computing Core",
			description: "",
			icon: null,
			locations: [],
		},
		{
			id: "t1-quantum-computing-lab",
			type: "label",
			category: "general",
			title: "T1 Quantum Computing Lab",
			description: "",
			icon: null,
			locations: [],
		},
		{
			id: "t2-teleportation-lab",
			type: "label",
			category: "general",
			title: "T2 Teleportation Lab",
			description: "",
			icon: null,
			locations: [],
		},
		{
			id: "t1-director's-office",
			type: "label",
			category: "general",
			title: "T1 Director's Office",
			description: "",
			icon: null,
			locations: [],
		},
		{
			id: "t2-sublevel-10",
			type: "label",
			category: "general",
			title: "T2 Sublevel 10",
			description: "",
			icon: null,
			locations: [],
		},
		{
			id: "t1-bioweapons-lab",
			type: "label",
			category: "general",
			title: "T1 Bioweapons Lab",
			description: "",
			icon: null,
			locations: [],
		},
		{
			id: "t3-rooftop",
			type: "label",
			category: "general",
			title: "T3 Rooftop",
			description: "",
			icon: null,
			locations: [],
		},
		{
			id: "t3-dark-aether-elements-vault-2",
			type: "label",
			category: "general",
			title: "T3 Dark Aether Elements Vault 2",
			description: "",
			icon: null,
			locations: [],
		},
	],
}

export default reckoning
