import type { MapConfig } from "@/data/interactive-map"
import { Option } from "effect"

export const config: MapConfig = {
	layers: [
		{
			id: "eidskallen",
			title: "Eidskallen",
			image: "/layers/totenreich/totenreich-eidskallen-layer.webp",
			markers: [
				{
					id: "eidskallen-landing",
					title: "Eidskallen Landing",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.551, y: 0.805 }],
				},
				{
					id: "fjord-road",
					title: "Fjord Road",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.451, y: 0.753 }],
				},
				{
					id: "dry-dock",
					title: "Dry Dock",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.347, y: 0.601 }],
				},
				{
					id: "titan-crane",
					title: "Titan Crane",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.316, y: 0.553 }],
				},
				{
					id: "core-foundry",
					title: "Core Foundry",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.278, y: 0.448 }],
				},
				{
					id: "war-factory",
					title: "War Factory",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.193, y: 0.444 }],
				},
				{
					id: "tyrs-foot",
					title: "Tyr's Foot",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.256, y: 0.313 }],
				},
				{
					id: "storm-bridge",
					title: "Storm Bridge",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.432, y: 0.289 }],
				},
				{
					id: "eidskallen-stave-church",
					title: "Eidskallen Stave Church",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.651, y: 0.348 }],
				},
				{
					id: "burial-grounds",
					title: "Burial Grounds",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.701, y: 0.351 }],
				},
				{
					id: "skallen-market",
					title: "Skallen Market",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.637, y: 0.432 }],
				},
				{
					id: "blodheim-hall",
					title: "Blodheim Hall",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.659, y: 0.553 }],
				},
				{
					id: "eidskallen-square",
					title: "Eidskallen Square",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.585, y: 0.589 }],
				},
				{
					id: "lovens-antiquities",
					title: "Loven's Antiquities",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.523, y: 0.566 }],
				},
				{
					id: "beacon-island",
					title: "Beacon Island",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.778, y: 0.685 }],
				},
				{
					id: "tyrs-head",
					title: "Tyr's Head",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.524, y: 0.15 }],
				},
				{
					id: "fishery-island",
					title: "Fishery Island",
					type: "label",
					category: "general",
					description: "",
					icon: Option.none(),
					locations: [{ x: 0.437, y: 0.423 }],
				},
				{
					id: "fishing-spot",
					title: "Fishing Spot",
					icon: Option.some("/icons/objectives/fish.webp"),
					category: "objectives",
					description:
						"Location where you can fish for items to get rewards, and potentially get a green fish spawn for the main quest.",
					locations: [
						{ x: 0.529, y: 0.838 },
						{ x: 0.621, y: 0.75 },
						{ x: 0.71, y: 0.771 },
						{ x: 0.871, y: 0.674 },
						{ x: 0.637, y: 0.621 },
						{ x: 0.504, y: 0.542 },
						{ x: 0.406, y: 0.564 },
						{ x: 0.443, y: 0.384 },
						{ x: 0.288, y: 0.334 },
						{ x: 0.508, y: 0.426 },
						{ x: 0.565, y: 0.329 },
					],
				},
			],
		},
		{
			id: "boss-fight-arena",
			title: "Boss Fight Arena",
			image: "/layers/totenreich/totenreich-boss-fight-arena-layer.webp",
			markers: [],
		},
	],
}
