/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-sqlite"
import {
	sqliteTable,
	index,
	uniqueIndex,
	foreignKey,
	integer,
	text,
	numeric,
} from "@payloadcms/db-sqlite/drizzle/sqlite-core"
import { sql, relations } from "@payloadcms/db-sqlite/drizzle"
import { randomUUID } from "crypto"

export const users_sessions = sqliteTable(
	"users_sessions",
	{
		_order: integer("_order").notNull(),
		_parentID: text("_parent_id").notNull(),
		id: text("id").primaryKey(),
		createdAt: text("created_at").default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		expiresAt: text("expires_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	},
	columns => ({
		_orderIdx: index("users_sessions_order_idx").on(columns._order),
		_parentIDIdx: index("users_sessions_parent_id_idx").on(columns._parentID),
		_parentIDFk: foreignKey({
			columns: [columns["_parentID"]],
			foreignColumns: [users.id],
			name: "users_sessions_parent_id_fk",
		}).onDelete("cascade"),
	}),
)

export const users = sqliteTable(
	"users",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		role: text("role", { enum: ["admin", "member"] })
			.notNull()
			.default("member"),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		email: text("email").notNull(),
		resetPasswordToken: text("reset_password_token"),
		resetPasswordExpiration: text("reset_password_expiration").default(
			sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
		),
		salt: text("salt"),
		hash: text("hash"),
		loginAttempts: numeric("login_attempts").default("0"),
		lockUntil: text("lock_until").default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	},
	columns => ({
		users_updated_at_idx: index("users_updated_at_idx").on(columns.updatedAt),
		users_created_at_idx: index("users_created_at_idx").on(columns.createdAt),
		users_email_idx: uniqueIndex("users_email_idx").on(columns.email),
	}),
)

export const media = sqliteTable(
	"media",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		title: text("title").notNull(),
		description: text("description"),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		url: text("url"),
		thumbnailURL: text("thumbnail_u_r_l"),
		filename: text("filename"),
		mimeType: text("mime_type"),
		filesize: numeric("filesize"),
		width: numeric("width"),
		height: numeric("height"),
		focalX: numeric("focal_x"),
		focalY: numeric("focal_y"),
	},
	columns => ({
		media_title_idx: index("media_title_idx").on(columns.title),
		media_updated_at_idx: index("media_updated_at_idx").on(columns.updatedAt),
		media_created_at_idx: index("media_created_at_idx").on(columns.createdAt),
		media_filename_idx: uniqueIndex("media_filename_idx").on(columns.filename),
	}),
)

export const maps = sqliteTable(
	"maps",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		title: text("title").notNull(),
		slug: text("slug").notNull(),
		releaseDate: text("release_date")
			.notNull()
			.default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		game: text("game_id")
			.notNull()
			.references(() => games.id, {
				onDelete: "set null",
			}),
		image: text("image_id")
			.notNull()
			.references(() => media.id, {
				onDelete: "set null",
			}),
		description: text("description").notNull(),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	},
	columns => ({
		maps_title_idx: index("maps_title_idx").on(columns.title),
		maps_slug_idx: uniqueIndex("maps_slug_idx").on(columns.slug),
		maps_release_date_idx: index("maps_release_date_idx").on(columns.releaseDate),
		maps_game_idx: index("maps_game_idx").on(columns.game),
		maps_image_idx: index("maps_image_idx").on(columns.image),
		maps_updated_at_idx: index("maps_updated_at_idx").on(columns.updatedAt),
		maps_created_at_idx: index("maps_created_at_idx").on(columns.createdAt),
	}),
)

export const games = sqliteTable(
	"games",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		title: text("title").notNull(),
		slug: text("slug").notNull(),
		releaseDate: text("release_date")
			.notNull()
			.default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		image: text("image_id")
			.notNull()
			.references(() => media.id, {
				onDelete: "set null",
			}),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	},
	columns => ({
		games_title_idx: index("games_title_idx").on(columns.title),
		games_slug_idx: uniqueIndex("games_slug_idx").on(columns.slug),
		games_release_date_idx: index("games_release_date_idx").on(columns.releaseDate),
		games_image_idx: index("games_image_idx").on(columns.image),
		games_updated_at_idx: index("games_updated_at_idx").on(columns.updatedAt),
		games_created_at_idx: index("games_created_at_idx").on(columns.createdAt),
	}),
)

export const main_quests = sqliteTable(
	"main_quests",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		title: text("title"),
		newAt: text("new_at").default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		state: text("state", { enum: ["Coming Soon", "New"] }),
		difficulty: text("difficulty", { enum: ["Easy", "Medium", "Hard"] }),
		map: text("map_id").references(() => maps.id, {
			onDelete: "set null",
		}),
		content: text("content", { mode: "json" }),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		_status: text("_status", { enum: ["draft", "published"] }).default("draft"),
	},
	columns => ({
		main_quests_title_idx: uniqueIndex("main_quests_title_idx").on(columns.title),
		main_quests_new_at_idx: index("main_quests_new_at_idx").on(columns.newAt),
		main_quests_map_idx: uniqueIndex("main_quests_map_idx").on(columns.map),
		main_quests_updated_at_idx: index("main_quests_updated_at_idx").on(columns.updatedAt),
		main_quests_created_at_idx: index("main_quests_created_at_idx").on(columns.createdAt),
		main_quests__status_idx: index("main_quests__status_idx").on(columns._status),
	}),
)

export const _main_quests_v = sqliteTable(
	"_main_quests_v",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		parent: text("parent_id").references(() => main_quests.id, {
			onDelete: "set null",
		}),
		version_title: text("version_title"),
		version_newAt: text("version_new_at").default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		version_state: text("version_state", { enum: ["Coming Soon", "New"] }),
		version_difficulty: text("version_difficulty", {
			enum: ["Easy", "Medium", "Hard"],
		}),
		version_map: text("version_map_id").references(() => maps.id, {
			onDelete: "set null",
		}),
		version_content: text("version_content", { mode: "json" }),
		version_updatedAt: text("version_updated_at").default(
			sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
		),
		version_createdAt: text("version_created_at").default(
			sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
		),
		version__status: text("version__status", {
			enum: ["draft", "published"],
		}).default("draft"),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		latest: integer("latest", { mode: "boolean" }),
	},
	columns => ({
		_main_quests_v_parent_idx: index("_main_quests_v_parent_idx").on(columns.parent),
		_main_quests_v_version_version_title_idx: index("_main_quests_v_version_version_title_idx").on(
			columns.version_title,
		),
		_main_quests_v_version_version_new_at_idx: index(
			"_main_quests_v_version_version_new_at_idx",
		).on(columns.version_newAt),
		_main_quests_v_version_version_map_idx: index("_main_quests_v_version_version_map_idx").on(
			columns.version_map,
		),
		_main_quests_v_version_version_updated_at_idx: index(
			"_main_quests_v_version_version_updated_at_idx",
		).on(columns.version_updatedAt),
		_main_quests_v_version_version_created_at_idx: index(
			"_main_quests_v_version_version_created_at_idx",
		).on(columns.version_createdAt),
		_main_quests_v_version_version__status_idx: index(
			"_main_quests_v_version_version__status_idx",
		).on(columns.version__status),
		_main_quests_v_created_at_idx: index("_main_quests_v_created_at_idx").on(columns.createdAt),
		_main_quests_v_updated_at_idx: index("_main_quests_v_updated_at_idx").on(columns.updatedAt),
		_main_quests_v_latest_idx: index("_main_quests_v_latest_idx").on(columns.latest),
	}),
)

export const side_quests = sqliteTable(
	"side_quests",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		title: text("title"),
		slug: text("slug"),
		newAt: text("new_at").default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		state: text("state", { enum: ["Coming Soon", "New"] }),
		map: text("map_id").references(() => maps.id, {
			onDelete: "set null",
		}),
		description: text("description"),
		content: text("content", { mode: "json" }),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		_status: text("_status", { enum: ["draft", "published"] }).default("draft"),
	},
	columns => ({
		side_quests_title_idx: index("side_quests_title_idx").on(columns.title),
		side_quests_slug_idx: uniqueIndex("side_quests_slug_idx").on(columns.slug),
		side_quests_new_at_idx: index("side_quests_new_at_idx").on(columns.newAt),
		side_quests_map_idx: index("side_quests_map_idx").on(columns.map),
		side_quests_updated_at_idx: index("side_quests_updated_at_idx").on(columns.updatedAt),
		side_quests_created_at_idx: index("side_quests_created_at_idx").on(columns.createdAt),
		side_quests__status_idx: index("side_quests__status_idx").on(columns._status),
	}),
)

export const _side_quests_v = sqliteTable(
	"_side_quests_v",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		parent: text("parent_id").references(() => side_quests.id, {
			onDelete: "set null",
		}),
		version_title: text("version_title"),
		version_slug: text("version_slug"),
		version_newAt: text("version_new_at").default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		version_state: text("version_state", { enum: ["Coming Soon", "New"] }),
		version_map: text("version_map_id").references(() => maps.id, {
			onDelete: "set null",
		}),
		version_description: text("version_description"),
		version_content: text("version_content", { mode: "json" }),
		version_updatedAt: text("version_updated_at").default(
			sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
		),
		version_createdAt: text("version_created_at").default(
			sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
		),
		version__status: text("version__status", {
			enum: ["draft", "published"],
		}).default("draft"),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		latest: integer("latest", { mode: "boolean" }),
	},
	columns => ({
		_side_quests_v_parent_idx: index("_side_quests_v_parent_idx").on(columns.parent),
		_side_quests_v_version_version_title_idx: index("_side_quests_v_version_version_title_idx").on(
			columns.version_title,
		),
		_side_quests_v_version_version_slug_idx: index("_side_quests_v_version_version_slug_idx").on(
			columns.version_slug,
		),
		_side_quests_v_version_version_new_at_idx: index(
			"_side_quests_v_version_version_new_at_idx",
		).on(columns.version_newAt),
		_side_quests_v_version_version_map_idx: index("_side_quests_v_version_version_map_idx").on(
			columns.version_map,
		),
		_side_quests_v_version_version_updated_at_idx: index(
			"_side_quests_v_version_version_updated_at_idx",
		).on(columns.version_updatedAt),
		_side_quests_v_version_version_created_at_idx: index(
			"_side_quests_v_version_version_created_at_idx",
		).on(columns.version_createdAt),
		_side_quests_v_version_version__status_idx: index(
			"_side_quests_v_version_version__status_idx",
		).on(columns.version__status),
		_side_quests_v_created_at_idx: index("_side_quests_v_created_at_idx").on(columns.createdAt),
		_side_quests_v_updated_at_idx: index("_side_quests_v_updated_at_idx").on(columns.updatedAt),
		_side_quests_v_latest_idx: index("_side_quests_v_latest_idx").on(columns.latest),
	}),
)

export const zombies = sqliteTable(
	"zombies",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		title: text("title"),
		slug: text("slug"),
		newAt: text("new_at").default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		state: text("state", { enum: ["Coming Soon", "New"] }),
		releaseDate: text("release_date").default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		image: text("image_id").references(() => media.id, {
			onDelete: "set null",
		}),
		description: text("description"),
		type: text("type", { enum: ["Normal", "Special", "Elite", "Boss"] }),
		speed: text("speed", { enum: ["Slow", "Medium", "Fast"] }),
		spawnBehavior: text("spawn_behavior"),
		combatStrategy: text("combat_strategy", { mode: "json" }),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		_status: text("_status", { enum: ["draft", "published"] }).default("draft"),
	},
	columns => ({
		zombies_title_idx: index("zombies_title_idx").on(columns.title),
		zombies_slug_idx: uniqueIndex("zombies_slug_idx").on(columns.slug),
		zombies_new_at_idx: index("zombies_new_at_idx").on(columns.newAt),
		zombies_release_date_idx: index("zombies_release_date_idx").on(columns.releaseDate),
		zombies_image_idx: index("zombies_image_idx").on(columns.image),
		zombies_updated_at_idx: index("zombies_updated_at_idx").on(columns.updatedAt),
		zombies_created_at_idx: index("zombies_created_at_idx").on(columns.createdAt),
		zombies__status_idx: index("zombies__status_idx").on(columns._status),
	}),
)

export const zombies_rels = sqliteTable(
	"zombies_rels",
	{
		id: integer("id").primaryKey(),
		order: integer("order"),
		parent: text("parent_id").notNull(),
		path: text("path").notNull(),
		gamesID: text("games_id"),
		mapsID: text("maps_id"),
		weakPointsID: text("weak_points_id"),
		ammoModsID: text("ammo_mods_id"),
		zombieAttacksID: text("zombie_attacks_id"),
	},
	columns => ({
		order: index("zombies_rels_order_idx").on(columns.order),
		parentIdx: index("zombies_rels_parent_idx").on(columns.parent),
		pathIdx: index("zombies_rels_path_idx").on(columns.path),
		zombies_rels_games_id_idx: index("zombies_rels_games_id_idx").on(columns.gamesID),
		zombies_rels_maps_id_idx: index("zombies_rels_maps_id_idx").on(columns.mapsID),
		zombies_rels_weak_points_id_idx: index("zombies_rels_weak_points_id_idx").on(
			columns.weakPointsID,
		),
		zombies_rels_ammo_mods_id_idx: index("zombies_rels_ammo_mods_id_idx").on(columns.ammoModsID),
		zombies_rels_zombie_attacks_id_idx: index("zombies_rels_zombie_attacks_id_idx").on(
			columns.zombieAttacksID,
		),
		parentFk: foreignKey({
			columns: [columns["parent"]],
			foreignColumns: [zombies.id],
			name: "zombies_rels_parent_fk",
		}).onDelete("cascade"),
		gamesIdFk: foreignKey({
			columns: [columns["gamesID"]],
			foreignColumns: [games.id],
			name: "zombies_rels_games_fk",
		}).onDelete("cascade"),
		mapsIdFk: foreignKey({
			columns: [columns["mapsID"]],
			foreignColumns: [maps.id],
			name: "zombies_rels_maps_fk",
		}).onDelete("cascade"),
		weakPointsIdFk: foreignKey({
			columns: [columns["weakPointsID"]],
			foreignColumns: [weak_points.id],
			name: "zombies_rels_weak_points_fk",
		}).onDelete("cascade"),
		ammoModsIdFk: foreignKey({
			columns: [columns["ammoModsID"]],
			foreignColumns: [ammo_mods.id],
			name: "zombies_rels_ammo_mods_fk",
		}).onDelete("cascade"),
		zombieAttacksIdFk: foreignKey({
			columns: [columns["zombieAttacksID"]],
			foreignColumns: [zombie_attacks.id],
			name: "zombies_rels_zombie_attacks_fk",
		}).onDelete("cascade"),
	}),
)

export const _zombies_v = sqliteTable(
	"_zombies_v",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		parent: text("parent_id").references(() => zombies.id, {
			onDelete: "set null",
		}),
		version_title: text("version_title"),
		version_slug: text("version_slug"),
		version_newAt: text("version_new_at").default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		version_state: text("version_state", { enum: ["Coming Soon", "New"] }),
		version_releaseDate: text("version_release_date").default(
			sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
		),
		version_image: text("version_image_id").references(() => media.id, {
			onDelete: "set null",
		}),
		version_description: text("version_description"),
		version_type: text("version_type", {
			enum: ["Normal", "Special", "Elite", "Boss"],
		}),
		version_speed: text("version_speed", { enum: ["Slow", "Medium", "Fast"] }),
		version_spawnBehavior: text("version_spawn_behavior"),
		version_combatStrategy: text("version_combat_strategy", { mode: "json" }),
		version_updatedAt: text("version_updated_at").default(
			sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
		),
		version_createdAt: text("version_created_at").default(
			sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
		),
		version__status: text("version__status", {
			enum: ["draft", "published"],
		}).default("draft"),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		latest: integer("latest", { mode: "boolean" }),
	},
	columns => ({
		_zombies_v_parent_idx: index("_zombies_v_parent_idx").on(columns.parent),
		_zombies_v_version_version_title_idx: index("_zombies_v_version_version_title_idx").on(
			columns.version_title,
		),
		_zombies_v_version_version_slug_idx: index("_zombies_v_version_version_slug_idx").on(
			columns.version_slug,
		),
		_zombies_v_version_version_new_at_idx: index("_zombies_v_version_version_new_at_idx").on(
			columns.version_newAt,
		),
		_zombies_v_version_version_release_date_idx: index(
			"_zombies_v_version_version_release_date_idx",
		).on(columns.version_releaseDate),
		_zombies_v_version_version_image_idx: index("_zombies_v_version_version_image_idx").on(
			columns.version_image,
		),
		_zombies_v_version_version_updated_at_idx: index(
			"_zombies_v_version_version_updated_at_idx",
		).on(columns.version_updatedAt),
		_zombies_v_version_version_created_at_idx: index(
			"_zombies_v_version_version_created_at_idx",
		).on(columns.version_createdAt),
		_zombies_v_version_version__status_idx: index("_zombies_v_version_version__status_idx").on(
			columns.version__status,
		),
		_zombies_v_created_at_idx: index("_zombies_v_created_at_idx").on(columns.createdAt),
		_zombies_v_updated_at_idx: index("_zombies_v_updated_at_idx").on(columns.updatedAt),
		_zombies_v_latest_idx: index("_zombies_v_latest_idx").on(columns.latest),
	}),
)

export const _zombies_v_rels = sqliteTable(
	"_zombies_v_rels",
	{
		id: integer("id").primaryKey(),
		order: integer("order"),
		parent: text("parent_id").notNull(),
		path: text("path").notNull(),
		gamesID: text("games_id"),
		mapsID: text("maps_id"),
		weakPointsID: text("weak_points_id"),
		ammoModsID: text("ammo_mods_id"),
		zombieAttacksID: text("zombie_attacks_id"),
	},
	columns => ({
		order: index("_zombies_v_rels_order_idx").on(columns.order),
		parentIdx: index("_zombies_v_rels_parent_idx").on(columns.parent),
		pathIdx: index("_zombies_v_rels_path_idx").on(columns.path),
		_zombies_v_rels_games_id_idx: index("_zombies_v_rels_games_id_idx").on(columns.gamesID),
		_zombies_v_rels_maps_id_idx: index("_zombies_v_rels_maps_id_idx").on(columns.mapsID),
		_zombies_v_rels_weak_points_id_idx: index("_zombies_v_rels_weak_points_id_idx").on(
			columns.weakPointsID,
		),
		_zombies_v_rels_ammo_mods_id_idx: index("_zombies_v_rels_ammo_mods_id_idx").on(
			columns.ammoModsID,
		),
		_zombies_v_rels_zombie_attacks_id_idx: index("_zombies_v_rels_zombie_attacks_id_idx").on(
			columns.zombieAttacksID,
		),
		parentFk: foreignKey({
			columns: [columns["parent"]],
			foreignColumns: [_zombies_v.id],
			name: "_zombies_v_rels_parent_fk",
		}).onDelete("cascade"),
		gamesIdFk: foreignKey({
			columns: [columns["gamesID"]],
			foreignColumns: [games.id],
			name: "_zombies_v_rels_games_fk",
		}).onDelete("cascade"),
		mapsIdFk: foreignKey({
			columns: [columns["mapsID"]],
			foreignColumns: [maps.id],
			name: "_zombies_v_rels_maps_fk",
		}).onDelete("cascade"),
		weakPointsIdFk: foreignKey({
			columns: [columns["weakPointsID"]],
			foreignColumns: [weak_points.id],
			name: "_zombies_v_rels_weak_points_fk",
		}).onDelete("cascade"),
		ammoModsIdFk: foreignKey({
			columns: [columns["ammoModsID"]],
			foreignColumns: [ammo_mods.id],
			name: "_zombies_v_rels_ammo_mods_fk",
		}).onDelete("cascade"),
		zombieAttacksIdFk: foreignKey({
			columns: [columns["zombieAttacksID"]],
			foreignColumns: [zombie_attacks.id],
			name: "_zombies_v_rels_zombie_attacks_fk",
		}).onDelete("cascade"),
	}),
)

export const zombie_attacks = sqliteTable(
	"zombie_attacks",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		title: text("title").notNull(),
		range: text("range", { enum: ["Short", "Medium", "Long"] }).notNull(),
		description: text("description").notNull(),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	},
	columns => ({
		zombie_attacks_title_idx: uniqueIndex("zombie_attacks_title_idx").on(columns.title),
		zombie_attacks_updated_at_idx: index("zombie_attacks_updated_at_idx").on(columns.updatedAt),
		zombie_attacks_created_at_idx: index("zombie_attacks_created_at_idx").on(columns.createdAt),
	}),
)

export const weak_points = sqliteTable(
	"weak_points",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		title: text("title").notNull(),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	},
	columns => ({
		weak_points_title_idx: uniqueIndex("weak_points_title_idx").on(columns.title),
		weak_points_updated_at_idx: index("weak_points_updated_at_idx").on(columns.updatedAt),
		weak_points_created_at_idx: index("weak_points_created_at_idx").on(columns.createdAt),
	}),
)

export const gobblegum = sqliteTable(
	"gobblegum",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		title: text("title").notNull(),
		rarity: text("rarity", {
			enum: [
				"Classic",
				"Mega",
				"Rare-Mega",
				"Ultra-Rare Mega",
				"Rare",
				"Epic",
				"Legendary",
				"Ultra",
			],
		}).notNull(),
		type: text("type", {
			enum: ["Round-Based", "Time-Based", "Immediate", "Player-Activated"],
		}).notNull(),
		game: text("game_id")
			.notNull()
			.references(() => games.id, {
				onDelete: "set null",
			}),
		image: text("image_id")
			.notNull()
			.references(() => media.id, {
				onDelete: "set null",
			}),
		description: text("description").notNull(),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	},
	columns => ({
		gobblegum_title_idx: index("gobblegum_title_idx").on(columns.title),
		gobblegum_game_idx: index("gobblegum_game_idx").on(columns.game),
		gobblegum_image_idx: index("gobblegum_image_idx").on(columns.image),
		gobblegum_updated_at_idx: index("gobblegum_updated_at_idx").on(columns.updatedAt),
		gobblegum_created_at_idx: index("gobblegum_created_at_idx").on(columns.createdAt),
	}),
)

export const perks = sqliteTable(
	"perks",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		title: text("title").notNull(),
		game: text("game_id")
			.notNull()
			.references(() => games.id, {
				onDelete: "set null",
			}),
		image: text("image_id")
			.notNull()
			.references(() => media.id, {
				onDelete: "set null",
			}),
		description: text("description").notNull(),
		modifier: text("modifier"),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	},
	columns => ({
		perks_title_idx: index("perks_title_idx").on(columns.title),
		perks_game_idx: index("perks_game_idx").on(columns.game),
		perks_image_idx: index("perks_image_idx").on(columns.image),
		perks_updated_at_idx: index("perks_updated_at_idx").on(columns.updatedAt),
		perks_created_at_idx: index("perks_created_at_idx").on(columns.createdAt),
	}),
)

export const ammo_mods = sqliteTable(
	"ammo_mods",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		title: text("title").notNull(),
		game: text("game_id")
			.notNull()
			.references(() => games.id, {
				onDelete: "set null",
			}),
		image: text("image_id")
			.notNull()
			.references(() => media.id, {
				onDelete: "set null",
			}),
		description: text("description").notNull(),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	},
	columns => ({
		ammo_mods_title_idx: index("ammo_mods_title_idx").on(columns.title),
		ammo_mods_game_idx: index("ammo_mods_game_idx").on(columns.game),
		ammo_mods_image_idx: index("ammo_mods_image_idx").on(columns.image),
		ammo_mods_updated_at_idx: index("ammo_mods_updated_at_idx").on(columns.updatedAt),
		ammo_mods_created_at_idx: index("ammo_mods_created_at_idx").on(columns.createdAt),
	}),
)

export const field_upgrades = sqliteTable(
	"field_upgrades",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		title: text("title").notNull(),
		game: text("game_id")
			.notNull()
			.references(() => games.id, {
				onDelete: "set null",
			}),
		image: text("image_id")
			.notNull()
			.references(() => media.id, {
				onDelete: "set null",
			}),
		description: text("description").notNull(),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	},
	columns => ({
		field_upgrades_title_idx: index("field_upgrades_title_idx").on(columns.title),
		field_upgrades_game_idx: index("field_upgrades_game_idx").on(columns.game),
		field_upgrades_image_idx: index("field_upgrades_image_idx").on(columns.image),
		field_upgrades_updated_at_idx: index("field_upgrades_updated_at_idx").on(columns.updatedAt),
		field_upgrades_created_at_idx: index("field_upgrades_created_at_idx").on(columns.createdAt),
	}),
)

export const augments = sqliteTable(
	"augments",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		title: text("title").notNull(),
		type: text("type", { enum: ["Major", "Minor"] }).notNull(),
		image: text("image_id")
			.notNull()
			.references(() => media.id, {
				onDelete: "set null",
			}),
		description: text("description").notNull(),
		perk: text("perk_id").references(() => perks.id, {
			onDelete: "set null",
		}),
		ammoMod: text("ammo_mod_id").references(() => ammo_mods.id, {
			onDelete: "set null",
		}),
		fieldUpgrade: text("field_upgrade_id").references(() => field_upgrades.id, {
			onDelete: "set null",
		}),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	},
	columns => ({
		augments_title_idx: index("augments_title_idx").on(columns.title),
		augments_image_idx: index("augments_image_idx").on(columns.image),
		augments_perk_idx: index("augments_perk_idx").on(columns.perk),
		augments_ammo_mod_idx: index("augments_ammo_mod_idx").on(columns.ammoMod),
		augments_field_upgrade_idx: index("augments_field_upgrade_idx").on(columns.fieldUpgrade),
		augments_updated_at_idx: index("augments_updated_at_idx").on(columns.updatedAt),
		augments_created_at_idx: index("augments_created_at_idx").on(columns.createdAt),
	}),
)

export const weapons = sqliteTable(
	"weapons",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		title: text("title").notNull(),
		image: text("image_id")
			.notNull()
			.references(() => media.id, {
				onDelete: "set null",
			}),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	},
	columns => ({
		weapons_title_idx: index("weapons_title_idx").on(columns.title),
		weapons_image_idx: index("weapons_image_idx").on(columns.image),
		weapons_updated_at_idx: index("weapons_updated_at_idx").on(columns.updatedAt),
		weapons_created_at_idx: index("weapons_created_at_idx").on(columns.createdAt),
	}),
)

export const weapons_rels = sqliteTable(
	"weapons_rels",
	{
		id: integer("id").primaryKey(),
		order: integer("order"),
		parent: text("parent_id").notNull(),
		path: text("path").notNull(),
		gamesID: text("games_id"),
	},
	columns => ({
		order: index("weapons_rels_order_idx").on(columns.order),
		parentIdx: index("weapons_rels_parent_idx").on(columns.parent),
		pathIdx: index("weapons_rels_path_idx").on(columns.path),
		weapons_rels_games_id_idx: index("weapons_rels_games_id_idx").on(columns.gamesID),
		parentFk: foreignKey({
			columns: [columns["parent"]],
			foreignColumns: [weapons.id],
			name: "weapons_rels_parent_fk",
		}).onDelete("cascade"),
		gamesIdFk: foreignKey({
			columns: [columns["gamesID"]],
			foreignColumns: [games.id],
			name: "weapons_rels_games_fk",
		}).onDelete("cascade"),
	}),
)

export const weapon_builds = sqliteTable(
	"weapon_builds",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		title: text("title").notNull(),
		weapon: text("weapon_id")
			.notNull()
			.references(() => weapons.id, {
				onDelete: "set null",
			}),
		buildCode: text("build_code"),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	},
	columns => ({
		weapon_builds_title_idx: index("weapon_builds_title_idx").on(columns.title),
		weapon_builds_weapon_idx: index("weapon_builds_weapon_idx").on(columns.weapon),
		weapon_builds_build_code_idx: uniqueIndex("weapon_builds_build_code_idx").on(columns.buildCode),
		weapon_builds_updated_at_idx: index("weapon_builds_updated_at_idx").on(columns.updatedAt),
		weapon_builds_created_at_idx: index("weapon_builds_created_at_idx").on(columns.createdAt),
	}),
)

export const weapon_builds_rels = sqliteTable(
	"weapon_builds_rels",
	{
		id: integer("id").primaryKey(),
		order: integer("order"),
		parent: text("parent_id").notNull(),
		path: text("path").notNull(),
		weaponAttachmentsID: text("weapon_attachments_id"),
	},
	columns => ({
		order: index("weapon_builds_rels_order_idx").on(columns.order),
		parentIdx: index("weapon_builds_rels_parent_idx").on(columns.parent),
		pathIdx: index("weapon_builds_rels_path_idx").on(columns.path),
		weapon_builds_rels_weapon_attachments_id_idx: index(
			"weapon_builds_rels_weapon_attachments_id_idx",
		).on(columns.weaponAttachmentsID),
		parentFk: foreignKey({
			columns: [columns["parent"]],
			foreignColumns: [weapon_builds.id],
			name: "weapon_builds_rels_parent_fk",
		}).onDelete("cascade"),
		weaponAttachmentsIdFk: foreignKey({
			columns: [columns["weaponAttachmentsID"]],
			foreignColumns: [weapon_attachments.id],
			name: "weapon_builds_rels_weapon_attachments_fk",
		}).onDelete("cascade"),
	}),
)

export const weapon_attachments = sqliteTable(
	"weapon_attachments",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		title: text("title").notNull(),
		type: text("type", {
			enum: [
				"Optic",
				"Muzzle",
				"Barrel",
				"Underbarrel",
				"Magazine",
				"Grip",
				"Comb",
				"Stock",
				"Laser",
				"Fire Mod",
			],
		}).notNull(),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	},
	columns => ({
		weapon_attachments_title_idx: uniqueIndex("weapon_attachments_title_idx").on(columns.title),
		weapon_attachments_updated_at_idx: index("weapon_attachments_updated_at_idx").on(
			columns.updatedAt,
		),
		weapon_attachments_created_at_idx: index("weapon_attachments_created_at_idx").on(
			columns.createdAt,
		),
	}),
)

export const legal = sqliteTable(
	"legal",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		title: text("title"),
		slug: text("slug"),
		content: text("content", { mode: "json" }),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		_status: text("_status", { enum: ["draft", "published"] }).default("draft"),
	},
	columns => ({
		legal_title_idx: index("legal_title_idx").on(columns.title),
		legal_slug_idx: uniqueIndex("legal_slug_idx").on(columns.slug),
		legal_updated_at_idx: index("legal_updated_at_idx").on(columns.updatedAt),
		legal_created_at_idx: index("legal_created_at_idx").on(columns.createdAt),
		legal__status_idx: index("legal__status_idx").on(columns._status),
	}),
)

export const _legal_v = sqliteTable(
	"_legal_v",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		parent: text("parent_id").references(() => legal.id, {
			onDelete: "set null",
		}),
		version_title: text("version_title"),
		version_slug: text("version_slug"),
		version_content: text("version_content", { mode: "json" }),
		version_updatedAt: text("version_updated_at").default(
			sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
		),
		version_createdAt: text("version_created_at").default(
			sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
		),
		version__status: text("version__status", {
			enum: ["draft", "published"],
		}).default("draft"),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		latest: integer("latest", { mode: "boolean" }),
	},
	columns => ({
		_legal_v_parent_idx: index("_legal_v_parent_idx").on(columns.parent),
		_legal_v_version_version_title_idx: index("_legal_v_version_version_title_idx").on(
			columns.version_title,
		),
		_legal_v_version_version_slug_idx: index("_legal_v_version_version_slug_idx").on(
			columns.version_slug,
		),
		_legal_v_version_version_updated_at_idx: index("_legal_v_version_version_updated_at_idx").on(
			columns.version_updatedAt,
		),
		_legal_v_version_version_created_at_idx: index("_legal_v_version_version_created_at_idx").on(
			columns.version_createdAt,
		),
		_legal_v_version_version__status_idx: index("_legal_v_version_version__status_idx").on(
			columns.version__status,
		),
		_legal_v_created_at_idx: index("_legal_v_created_at_idx").on(columns.createdAt),
		_legal_v_updated_at_idx: index("_legal_v_updated_at_idx").on(columns.updatedAt),
		_legal_v_latest_idx: index("_legal_v_latest_idx").on(columns.latest),
	}),
)

export const payload_locked_documents = sqliteTable(
	"payload_locked_documents",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		globalSlug: text("global_slug"),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	},
	columns => ({
		payload_locked_documents_global_slug_idx: index("payload_locked_documents_global_slug_idx").on(
			columns.globalSlug,
		),
		payload_locked_documents_updated_at_idx: index("payload_locked_documents_updated_at_idx").on(
			columns.updatedAt,
		),
		payload_locked_documents_created_at_idx: index("payload_locked_documents_created_at_idx").on(
			columns.createdAt,
		),
	}),
)

export const payload_locked_documents_rels = sqliteTable(
	"payload_locked_documents_rels",
	{
		id: integer("id").primaryKey(),
		order: integer("order"),
		parent: text("parent_id").notNull(),
		path: text("path").notNull(),
		usersID: text("users_id"),
		mediaID: text("media_id"),
		mapsID: text("maps_id"),
		gamesID: text("games_id"),
		mainQuestsID: text("main_quests_id"),
		sideQuestsID: text("side_quests_id"),
		zombiesID: text("zombies_id"),
		zombieAttacksID: text("zombie_attacks_id"),
		weakPointsID: text("weak_points_id"),
		gobblegumID: text("gobblegum_id"),
		perksID: text("perks_id"),
		ammoModsID: text("ammo_mods_id"),
		fieldUpgradesID: text("field_upgrades_id"),
		augmentsID: text("augments_id"),
		weaponsID: text("weapons_id"),
		weaponBuildsID: text("weapon_builds_id"),
		weaponAttachmentsID: text("weapon_attachments_id"),
		legalID: text("legal_id"),
	},
	columns => ({
		order: index("payload_locked_documents_rels_order_idx").on(columns.order),
		parentIdx: index("payload_locked_documents_rels_parent_idx").on(columns.parent),
		pathIdx: index("payload_locked_documents_rels_path_idx").on(columns.path),
		payload_locked_documents_rels_users_id_idx: index(
			"payload_locked_documents_rels_users_id_idx",
		).on(columns.usersID),
		payload_locked_documents_rels_media_id_idx: index(
			"payload_locked_documents_rels_media_id_idx",
		).on(columns.mediaID),
		payload_locked_documents_rels_maps_id_idx: index(
			"payload_locked_documents_rels_maps_id_idx",
		).on(columns.mapsID),
		payload_locked_documents_rels_games_id_idx: index(
			"payload_locked_documents_rels_games_id_idx",
		).on(columns.gamesID),
		payload_locked_documents_rels_main_quests_id_idx: index(
			"payload_locked_documents_rels_main_quests_id_idx",
		).on(columns.mainQuestsID),
		payload_locked_documents_rels_side_quests_id_idx: index(
			"payload_locked_documents_rels_side_quests_id_idx",
		).on(columns.sideQuestsID),
		payload_locked_documents_rels_zombies_id_idx: index(
			"payload_locked_documents_rels_zombies_id_idx",
		).on(columns.zombiesID),
		payload_locked_documents_rels_zombie_attacks_id_idx: index(
			"payload_locked_documents_rels_zombie_attacks_id_idx",
		).on(columns.zombieAttacksID),
		payload_locked_documents_rels_weak_points_id_idx: index(
			"payload_locked_documents_rels_weak_points_id_idx",
		).on(columns.weakPointsID),
		payload_locked_documents_rels_gobblegum_id_idx: index(
			"payload_locked_documents_rels_gobblegum_id_idx",
		).on(columns.gobblegumID),
		payload_locked_documents_rels_perks_id_idx: index(
			"payload_locked_documents_rels_perks_id_idx",
		).on(columns.perksID),
		payload_locked_documents_rels_ammo_mods_id_idx: index(
			"payload_locked_documents_rels_ammo_mods_id_idx",
		).on(columns.ammoModsID),
		payload_locked_documents_rels_field_upgrades_id_idx: index(
			"payload_locked_documents_rels_field_upgrades_id_idx",
		).on(columns.fieldUpgradesID),
		payload_locked_documents_rels_augments_id_idx: index(
			"payload_locked_documents_rels_augments_id_idx",
		).on(columns.augmentsID),
		payload_locked_documents_rels_weapons_id_idx: index(
			"payload_locked_documents_rels_weapons_id_idx",
		).on(columns.weaponsID),
		payload_locked_documents_rels_weapon_builds_id_idx: index(
			"payload_locked_documents_rels_weapon_builds_id_idx",
		).on(columns.weaponBuildsID),
		payload_locked_documents_rels_weapon_attachments_id_idx: index(
			"payload_locked_documents_rels_weapon_attachments_id_idx",
		).on(columns.weaponAttachmentsID),
		payload_locked_documents_rels_legal_id_idx: index(
			"payload_locked_documents_rels_legal_id_idx",
		).on(columns.legalID),
		parentFk: foreignKey({
			columns: [columns["parent"]],
			foreignColumns: [payload_locked_documents.id],
			name: "payload_locked_documents_rels_parent_fk",
		}).onDelete("cascade"),
		usersIdFk: foreignKey({
			columns: [columns["usersID"]],
			foreignColumns: [users.id],
			name: "payload_locked_documents_rels_users_fk",
		}).onDelete("cascade"),
		mediaIdFk: foreignKey({
			columns: [columns["mediaID"]],
			foreignColumns: [media.id],
			name: "payload_locked_documents_rels_media_fk",
		}).onDelete("cascade"),
		mapsIdFk: foreignKey({
			columns: [columns["mapsID"]],
			foreignColumns: [maps.id],
			name: "payload_locked_documents_rels_maps_fk",
		}).onDelete("cascade"),
		gamesIdFk: foreignKey({
			columns: [columns["gamesID"]],
			foreignColumns: [games.id],
			name: "payload_locked_documents_rels_games_fk",
		}).onDelete("cascade"),
		mainQuestsIdFk: foreignKey({
			columns: [columns["mainQuestsID"]],
			foreignColumns: [main_quests.id],
			name: "payload_locked_documents_rels_main_quests_fk",
		}).onDelete("cascade"),
		sideQuestsIdFk: foreignKey({
			columns: [columns["sideQuestsID"]],
			foreignColumns: [side_quests.id],
			name: "payload_locked_documents_rels_side_quests_fk",
		}).onDelete("cascade"),
		zombiesIdFk: foreignKey({
			columns: [columns["zombiesID"]],
			foreignColumns: [zombies.id],
			name: "payload_locked_documents_rels_zombies_fk",
		}).onDelete("cascade"),
		zombieAttacksIdFk: foreignKey({
			columns: [columns["zombieAttacksID"]],
			foreignColumns: [zombie_attacks.id],
			name: "payload_locked_documents_rels_zombie_attacks_fk",
		}).onDelete("cascade"),
		weakPointsIdFk: foreignKey({
			columns: [columns["weakPointsID"]],
			foreignColumns: [weak_points.id],
			name: "payload_locked_documents_rels_weak_points_fk",
		}).onDelete("cascade"),
		gobblegumIdFk: foreignKey({
			columns: [columns["gobblegumID"]],
			foreignColumns: [gobblegum.id],
			name: "payload_locked_documents_rels_gobblegum_fk",
		}).onDelete("cascade"),
		perksIdFk: foreignKey({
			columns: [columns["perksID"]],
			foreignColumns: [perks.id],
			name: "payload_locked_documents_rels_perks_fk",
		}).onDelete("cascade"),
		ammoModsIdFk: foreignKey({
			columns: [columns["ammoModsID"]],
			foreignColumns: [ammo_mods.id],
			name: "payload_locked_documents_rels_ammo_mods_fk",
		}).onDelete("cascade"),
		fieldUpgradesIdFk: foreignKey({
			columns: [columns["fieldUpgradesID"]],
			foreignColumns: [field_upgrades.id],
			name: "payload_locked_documents_rels_field_upgrades_fk",
		}).onDelete("cascade"),
		augmentsIdFk: foreignKey({
			columns: [columns["augmentsID"]],
			foreignColumns: [augments.id],
			name: "payload_locked_documents_rels_augments_fk",
		}).onDelete("cascade"),
		weaponsIdFk: foreignKey({
			columns: [columns["weaponsID"]],
			foreignColumns: [weapons.id],
			name: "payload_locked_documents_rels_weapons_fk",
		}).onDelete("cascade"),
		weaponBuildsIdFk: foreignKey({
			columns: [columns["weaponBuildsID"]],
			foreignColumns: [weapon_builds.id],
			name: "payload_locked_documents_rels_weapon_builds_fk",
		}).onDelete("cascade"),
		weaponAttachmentsIdFk: foreignKey({
			columns: [columns["weaponAttachmentsID"]],
			foreignColumns: [weapon_attachments.id],
			name: "payload_locked_documents_rels_weapon_attachments_fk",
		}).onDelete("cascade"),
		legalIdFk: foreignKey({
			columns: [columns["legalID"]],
			foreignColumns: [legal.id],
			name: "payload_locked_documents_rels_legal_fk",
		}).onDelete("cascade"),
	}),
)

export const payload_preferences = sqliteTable(
	"payload_preferences",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		key: text("key"),
		value: text("value", { mode: "json" }),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	},
	columns => ({
		payload_preferences_key_idx: index("payload_preferences_key_idx").on(columns.key),
		payload_preferences_updated_at_idx: index("payload_preferences_updated_at_idx").on(
			columns.updatedAt,
		),
		payload_preferences_created_at_idx: index("payload_preferences_created_at_idx").on(
			columns.createdAt,
		),
	}),
)

export const payload_preferences_rels = sqliteTable(
	"payload_preferences_rels",
	{
		id: integer("id").primaryKey(),
		order: integer("order"),
		parent: text("parent_id").notNull(),
		path: text("path").notNull(),
		usersID: text("users_id"),
	},
	columns => ({
		order: index("payload_preferences_rels_order_idx").on(columns.order),
		parentIdx: index("payload_preferences_rels_parent_idx").on(columns.parent),
		pathIdx: index("payload_preferences_rels_path_idx").on(columns.path),
		payload_preferences_rels_users_id_idx: index("payload_preferences_rels_users_id_idx").on(
			columns.usersID,
		),
		parentFk: foreignKey({
			columns: [columns["parent"]],
			foreignColumns: [payload_preferences.id],
			name: "payload_preferences_rels_parent_fk",
		}).onDelete("cascade"),
		usersIdFk: foreignKey({
			columns: [columns["usersID"]],
			foreignColumns: [users.id],
			name: "payload_preferences_rels_users_fk",
		}).onDelete("cascade"),
	}),
)

export const payload_migrations = sqliteTable(
	"payload_migrations",
	{
		id: text("id")
			.primaryKey()
			.$defaultFn(() => randomUUID()),
		name: text("name"),
		batch: numeric("batch"),
		updatedAt: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
		createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	},
	columns => ({
		payload_migrations_updated_at_idx: index("payload_migrations_updated_at_idx").on(
			columns.updatedAt,
		),
		payload_migrations_created_at_idx: index("payload_migrations_created_at_idx").on(
			columns.createdAt,
		),
	}),
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
	_parentID: one(users, {
		fields: [users_sessions._parentID],
		references: [users.id],
		relationName: "sessions",
	}),
}))
export const relations_users = relations(users, ({ many }) => ({
	sessions: many(users_sessions, {
		relationName: "sessions",
	}),
}))
export const relations_media = relations(media, () => ({}))
export const relations_maps = relations(maps, ({ one }) => ({
	game: one(games, {
		fields: [maps.game],
		references: [games.id],
		relationName: "game",
	}),
	image: one(media, {
		fields: [maps.image],
		references: [media.id],
		relationName: "image",
	}),
}))
export const relations_games = relations(games, ({ one }) => ({
	image: one(media, {
		fields: [games.image],
		references: [media.id],
		relationName: "image",
	}),
}))
export const relations_main_quests = relations(main_quests, ({ one }) => ({
	map: one(maps, {
		fields: [main_quests.map],
		references: [maps.id],
		relationName: "map",
	}),
}))
export const relations__main_quests_v = relations(_main_quests_v, ({ one }) => ({
	parent: one(main_quests, {
		fields: [_main_quests_v.parent],
		references: [main_quests.id],
		relationName: "parent",
	}),
	version_map: one(maps, {
		fields: [_main_quests_v.version_map],
		references: [maps.id],
		relationName: "version_map",
	}),
}))
export const relations_side_quests = relations(side_quests, ({ one }) => ({
	map: one(maps, {
		fields: [side_quests.map],
		references: [maps.id],
		relationName: "map",
	}),
}))
export const relations__side_quests_v = relations(_side_quests_v, ({ one }) => ({
	parent: one(side_quests, {
		fields: [_side_quests_v.parent],
		references: [side_quests.id],
		relationName: "parent",
	}),
	version_map: one(maps, {
		fields: [_side_quests_v.version_map],
		references: [maps.id],
		relationName: "version_map",
	}),
}))
export const relations_zombies_rels = relations(zombies_rels, ({ one }) => ({
	parent: one(zombies, {
		fields: [zombies_rels.parent],
		references: [zombies.id],
		relationName: "_rels",
	}),
	gamesID: one(games, {
		fields: [zombies_rels.gamesID],
		references: [games.id],
		relationName: "games",
	}),
	mapsID: one(maps, {
		fields: [zombies_rels.mapsID],
		references: [maps.id],
		relationName: "maps",
	}),
	weakPointsID: one(weak_points, {
		fields: [zombies_rels.weakPointsID],
		references: [weak_points.id],
		relationName: "weakPoints",
	}),
	ammoModsID: one(ammo_mods, {
		fields: [zombies_rels.ammoModsID],
		references: [ammo_mods.id],
		relationName: "ammoMods",
	}),
	zombieAttacksID: one(zombie_attacks, {
		fields: [zombies_rels.zombieAttacksID],
		references: [zombie_attacks.id],
		relationName: "zombieAttacks",
	}),
}))
export const relations_zombies = relations(zombies, ({ one, many }) => ({
	image: one(media, {
		fields: [zombies.image],
		references: [media.id],
		relationName: "image",
	}),
	_rels: many(zombies_rels, {
		relationName: "_rels",
	}),
}))
export const relations__zombies_v_rels = relations(_zombies_v_rels, ({ one }) => ({
	parent: one(_zombies_v, {
		fields: [_zombies_v_rels.parent],
		references: [_zombies_v.id],
		relationName: "_rels",
	}),
	gamesID: one(games, {
		fields: [_zombies_v_rels.gamesID],
		references: [games.id],
		relationName: "games",
	}),
	mapsID: one(maps, {
		fields: [_zombies_v_rels.mapsID],
		references: [maps.id],
		relationName: "maps",
	}),
	weakPointsID: one(weak_points, {
		fields: [_zombies_v_rels.weakPointsID],
		references: [weak_points.id],
		relationName: "weakPoints",
	}),
	ammoModsID: one(ammo_mods, {
		fields: [_zombies_v_rels.ammoModsID],
		references: [ammo_mods.id],
		relationName: "ammoMods",
	}),
	zombieAttacksID: one(zombie_attacks, {
		fields: [_zombies_v_rels.zombieAttacksID],
		references: [zombie_attacks.id],
		relationName: "zombieAttacks",
	}),
}))
export const relations__zombies_v = relations(_zombies_v, ({ one, many }) => ({
	parent: one(zombies, {
		fields: [_zombies_v.parent],
		references: [zombies.id],
		relationName: "parent",
	}),
	version_image: one(media, {
		fields: [_zombies_v.version_image],
		references: [media.id],
		relationName: "version_image",
	}),
	_rels: many(_zombies_v_rels, {
		relationName: "_rels",
	}),
}))
export const relations_zombie_attacks = relations(zombie_attacks, () => ({}))
export const relations_weak_points = relations(weak_points, () => ({}))
export const relations_gobblegum = relations(gobblegum, ({ one }) => ({
	game: one(games, {
		fields: [gobblegum.game],
		references: [games.id],
		relationName: "game",
	}),
	image: one(media, {
		fields: [gobblegum.image],
		references: [media.id],
		relationName: "image",
	}),
}))
export const relations_perks = relations(perks, ({ one }) => ({
	game: one(games, {
		fields: [perks.game],
		references: [games.id],
		relationName: "game",
	}),
	image: one(media, {
		fields: [perks.image],
		references: [media.id],
		relationName: "image",
	}),
}))
export const relations_ammo_mods = relations(ammo_mods, ({ one }) => ({
	game: one(games, {
		fields: [ammo_mods.game],
		references: [games.id],
		relationName: "game",
	}),
	image: one(media, {
		fields: [ammo_mods.image],
		references: [media.id],
		relationName: "image",
	}),
}))
export const relations_field_upgrades = relations(field_upgrades, ({ one }) => ({
	game: one(games, {
		fields: [field_upgrades.game],
		references: [games.id],
		relationName: "game",
	}),
	image: one(media, {
		fields: [field_upgrades.image],
		references: [media.id],
		relationName: "image",
	}),
}))
export const relations_augments = relations(augments, ({ one }) => ({
	image: one(media, {
		fields: [augments.image],
		references: [media.id],
		relationName: "image",
	}),
	perk: one(perks, {
		fields: [augments.perk],
		references: [perks.id],
		relationName: "perk",
	}),
	ammoMod: one(ammo_mods, {
		fields: [augments.ammoMod],
		references: [ammo_mods.id],
		relationName: "ammoMod",
	}),
	fieldUpgrade: one(field_upgrades, {
		fields: [augments.fieldUpgrade],
		references: [field_upgrades.id],
		relationName: "fieldUpgrade",
	}),
}))
export const relations_weapons_rels = relations(weapons_rels, ({ one }) => ({
	parent: one(weapons, {
		fields: [weapons_rels.parent],
		references: [weapons.id],
		relationName: "_rels",
	}),
	gamesID: one(games, {
		fields: [weapons_rels.gamesID],
		references: [games.id],
		relationName: "games",
	}),
}))
export const relations_weapons = relations(weapons, ({ one, many }) => ({
	image: one(media, {
		fields: [weapons.image],
		references: [media.id],
		relationName: "image",
	}),
	_rels: many(weapons_rels, {
		relationName: "_rels",
	}),
}))
export const relations_weapon_builds_rels = relations(weapon_builds_rels, ({ one }) => ({
	parent: one(weapon_builds, {
		fields: [weapon_builds_rels.parent],
		references: [weapon_builds.id],
		relationName: "_rels",
	}),
	weaponAttachmentsID: one(weapon_attachments, {
		fields: [weapon_builds_rels.weaponAttachmentsID],
		references: [weapon_attachments.id],
		relationName: "weaponAttachments",
	}),
}))
export const relations_weapon_builds = relations(weapon_builds, ({ one, many }) => ({
	weapon: one(weapons, {
		fields: [weapon_builds.weapon],
		references: [weapons.id],
		relationName: "weapon",
	}),
	_rels: many(weapon_builds_rels, {
		relationName: "_rels",
	}),
}))
export const relations_weapon_attachments = relations(weapon_attachments, () => ({}))
export const relations_legal = relations(legal, () => ({}))
export const relations__legal_v = relations(_legal_v, ({ one }) => ({
	parent: one(legal, {
		fields: [_legal_v.parent],
		references: [legal.id],
		relationName: "parent",
	}),
}))
export const relations_payload_locked_documents_rels = relations(
	payload_locked_documents_rels,
	({ one }) => ({
		parent: one(payload_locked_documents, {
			fields: [payload_locked_documents_rels.parent],
			references: [payload_locked_documents.id],
			relationName: "_rels",
		}),
		usersID: one(users, {
			fields: [payload_locked_documents_rels.usersID],
			references: [users.id],
			relationName: "users",
		}),
		mediaID: one(media, {
			fields: [payload_locked_documents_rels.mediaID],
			references: [media.id],
			relationName: "media",
		}),
		mapsID: one(maps, {
			fields: [payload_locked_documents_rels.mapsID],
			references: [maps.id],
			relationName: "maps",
		}),
		gamesID: one(games, {
			fields: [payload_locked_documents_rels.gamesID],
			references: [games.id],
			relationName: "games",
		}),
		mainQuestsID: one(main_quests, {
			fields: [payload_locked_documents_rels.mainQuestsID],
			references: [main_quests.id],
			relationName: "mainQuests",
		}),
		sideQuestsID: one(side_quests, {
			fields: [payload_locked_documents_rels.sideQuestsID],
			references: [side_quests.id],
			relationName: "sideQuests",
		}),
		zombiesID: one(zombies, {
			fields: [payload_locked_documents_rels.zombiesID],
			references: [zombies.id],
			relationName: "zombies",
		}),
		zombieAttacksID: one(zombie_attacks, {
			fields: [payload_locked_documents_rels.zombieAttacksID],
			references: [zombie_attacks.id],
			relationName: "zombieAttacks",
		}),
		weakPointsID: one(weak_points, {
			fields: [payload_locked_documents_rels.weakPointsID],
			references: [weak_points.id],
			relationName: "weakPoints",
		}),
		gobblegumID: one(gobblegum, {
			fields: [payload_locked_documents_rels.gobblegumID],
			references: [gobblegum.id],
			relationName: "gobblegum",
		}),
		perksID: one(perks, {
			fields: [payload_locked_documents_rels.perksID],
			references: [perks.id],
			relationName: "perks",
		}),
		ammoModsID: one(ammo_mods, {
			fields: [payload_locked_documents_rels.ammoModsID],
			references: [ammo_mods.id],
			relationName: "ammoMods",
		}),
		fieldUpgradesID: one(field_upgrades, {
			fields: [payload_locked_documents_rels.fieldUpgradesID],
			references: [field_upgrades.id],
			relationName: "fieldUpgrades",
		}),
		augmentsID: one(augments, {
			fields: [payload_locked_documents_rels.augmentsID],
			references: [augments.id],
			relationName: "augments",
		}),
		weaponsID: one(weapons, {
			fields: [payload_locked_documents_rels.weaponsID],
			references: [weapons.id],
			relationName: "weapons",
		}),
		weaponBuildsID: one(weapon_builds, {
			fields: [payload_locked_documents_rels.weaponBuildsID],
			references: [weapon_builds.id],
			relationName: "weaponBuilds",
		}),
		weaponAttachmentsID: one(weapon_attachments, {
			fields: [payload_locked_documents_rels.weaponAttachmentsID],
			references: [weapon_attachments.id],
			relationName: "weaponAttachments",
		}),
		legalID: one(legal, {
			fields: [payload_locked_documents_rels.legalID],
			references: [legal.id],
			relationName: "legal",
		}),
	}),
)
export const relations_payload_locked_documents = relations(
	payload_locked_documents,
	({ many }) => ({
		_rels: many(payload_locked_documents_rels, {
			relationName: "_rels",
		}),
	}),
)
export const relations_payload_preferences_rels = relations(
	payload_preferences_rels,
	({ one }) => ({
		parent: one(payload_preferences, {
			fields: [payload_preferences_rels.parent],
			references: [payload_preferences.id],
			relationName: "_rels",
		}),
		usersID: one(users, {
			fields: [payload_preferences_rels.usersID],
			references: [users.id],
			relationName: "users",
		}),
	}),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
	_rels: many(payload_preferences_rels, {
		relationName: "_rels",
	}),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
	users_sessions: typeof users_sessions
	users: typeof users
	media: typeof media
	maps: typeof maps
	games: typeof games
	main_quests: typeof main_quests
	_main_quests_v: typeof _main_quests_v
	side_quests: typeof side_quests
	_side_quests_v: typeof _side_quests_v
	zombies: typeof zombies
	zombies_rels: typeof zombies_rels
	_zombies_v: typeof _zombies_v
	_zombies_v_rels: typeof _zombies_v_rels
	zombie_attacks: typeof zombie_attacks
	weak_points: typeof weak_points
	gobblegum: typeof gobblegum
	perks: typeof perks
	ammo_mods: typeof ammo_mods
	field_upgrades: typeof field_upgrades
	augments: typeof augments
	weapons: typeof weapons
	weapons_rels: typeof weapons_rels
	weapon_builds: typeof weapon_builds
	weapon_builds_rels: typeof weapon_builds_rels
	weapon_attachments: typeof weapon_attachments
	legal: typeof legal
	_legal_v: typeof _legal_v
	payload_locked_documents: typeof payload_locked_documents
	payload_locked_documents_rels: typeof payload_locked_documents_rels
	payload_preferences: typeof payload_preferences
	payload_preferences_rels: typeof payload_preferences_rels
	payload_migrations: typeof payload_migrations
	relations_users_sessions: typeof relations_users_sessions
	relations_users: typeof relations_users
	relations_media: typeof relations_media
	relations_maps: typeof relations_maps
	relations_games: typeof relations_games
	relations_main_quests: typeof relations_main_quests
	relations__main_quests_v: typeof relations__main_quests_v
	relations_side_quests: typeof relations_side_quests
	relations__side_quests_v: typeof relations__side_quests_v
	relations_zombies_rels: typeof relations_zombies_rels
	relations_zombies: typeof relations_zombies
	relations__zombies_v_rels: typeof relations__zombies_v_rels
	relations__zombies_v: typeof relations__zombies_v
	relations_zombie_attacks: typeof relations_zombie_attacks
	relations_weak_points: typeof relations_weak_points
	relations_gobblegum: typeof relations_gobblegum
	relations_perks: typeof relations_perks
	relations_ammo_mods: typeof relations_ammo_mods
	relations_field_upgrades: typeof relations_field_upgrades
	relations_augments: typeof relations_augments
	relations_weapons_rels: typeof relations_weapons_rels
	relations_weapons: typeof relations_weapons
	relations_weapon_builds_rels: typeof relations_weapon_builds_rels
	relations_weapon_builds: typeof relations_weapon_builds
	relations_weapon_attachments: typeof relations_weapon_attachments
	relations_legal: typeof relations_legal
	relations__legal_v: typeof relations__legal_v
	relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
	relations_payload_locked_documents: typeof relations_payload_locked_documents
	relations_payload_preferences_rels: typeof relations_payload_preferences_rels
	relations_payload_preferences: typeof relations_payload_preferences
	relations_payload_migrations: typeof relations_payload_migrations
}

declare module "@payloadcms/db-sqlite" {
	export interface GeneratedDatabaseSchema {
		schema: DatabaseSchema
	}
}
