/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SideQuestsRouteImport } from './routes/side-quests'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RelicsRouteImport } from './routes/relics'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as MainQuestsRouteImport } from './routes/main-quests'
import { Route as BestiaryRouteImport } from './routes/bestiary'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SideQuestsIndexRouteImport } from './routes/side-quests.index'
import { Route as RelicsIndexRouteImport } from './routes/relics.index'
import { Route as MapsIndexRouteImport } from './routes/maps.index'
import { Route as MainQuestsIndexRouteImport } from './routes/main-quests.index'
import { Route as BestiaryIndexRouteImport } from './routes/bestiary.index'
import { Route as NewsletterUnsubscribeRouteImport } from './routes/newsletter.unsubscribe'
import { Route as MapsMapIdRouteImport } from './routes/maps.$mapId'
import { Route as BestiaryZombieIdRouteImport } from './routes/bestiary.$zombieId'
import { Route as NewsletterUnsubscribeIndexRouteImport } from './routes/newsletter.unsubscribe.index'
import { Route as RelicsGameIdRelicIdRouteImport } from './routes/relics.$gameId.$relicId'
import { Route as NewsletterUnsubscribeSuccessRouteImport } from './routes/newsletter.unsubscribe.success'
import { Route as NewsletterUnsubscribeErrorRouteImport } from './routes/newsletter.unsubscribe.error'
import { Route as NewsletterSubscribeSuccessRouteImport } from './routes/newsletter.subscribe.success'
import { Route as NewsletterSubscribeErrorRouteImport } from './routes/newsletter.subscribe.error'
import { Route as MainQuestsGameIdMapIdRouteImport } from './routes/main-quests.$gameId.$mapId'
import { Route as ApiNewsletterUnsubscribeRouteImport } from './routes/api.newsletter.unsubscribe'
import { Route as ApiNewsletterSubscribeRouteImport } from './routes/api.newsletter.subscribe'
import { Route as SideQuestsGameIdMapIdQuestIdRouteImport } from './routes/side-quests.$gameId.$mapId.$questId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SideQuestsRoute = SideQuestsRouteImport.update({
  id: '/side-quests',
  path: '/side-quests',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RelicsRoute = RelicsRouteImport.update({
  id: '/relics',
  path: '/relics',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const MainQuestsRoute = MainQuestsRouteImport.update({
  id: '/main-quests',
  path: '/main-quests',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryRoute = BestiaryRouteImport.update({
  id: '/bestiary',
  path: '/bestiary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SideQuestsIndexRoute = SideQuestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SideQuestsRoute,
} as any)
const RelicsIndexRoute = RelicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RelicsRoute,
} as any)
const MapsIndexRoute = MapsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MapsRoute,
} as any)
const MainQuestsIndexRoute = MainQuestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainQuestsRoute,
} as any)
const BestiaryIndexRoute = BestiaryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BestiaryRoute,
} as any)
const NewsletterUnsubscribeRoute = NewsletterUnsubscribeRouteImport.update({
  id: '/newsletter/unsubscribe',
  path: '/newsletter/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsMapIdRoute = MapsMapIdRouteImport.update({
  id: '/$mapId',
  path: '/$mapId',
  getParentRoute: () => MapsRoute,
} as any)
const BestiaryZombieIdRoute = BestiaryZombieIdRouteImport.update({
  id: '/$zombieId',
  path: '/$zombieId',
  getParentRoute: () => BestiaryRoute,
} as any)
const NewsletterUnsubscribeIndexRoute =
  NewsletterUnsubscribeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NewsletterUnsubscribeRoute,
  } as any)
const RelicsGameIdRelicIdRoute = RelicsGameIdRelicIdRouteImport.update({
  id: '/$gameId/$relicId',
  path: '/$gameId/$relicId',
  getParentRoute: () => RelicsRoute,
} as any)
const NewsletterUnsubscribeSuccessRoute =
  NewsletterUnsubscribeSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => NewsletterUnsubscribeRoute,
  } as any)
const NewsletterUnsubscribeErrorRoute =
  NewsletterUnsubscribeErrorRouteImport.update({
    id: '/error',
    path: '/error',
    getParentRoute: () => NewsletterUnsubscribeRoute,
  } as any)
const NewsletterSubscribeSuccessRoute =
  NewsletterSubscribeSuccessRouteImport.update({
    id: '/newsletter/subscribe/success',
    path: '/newsletter/subscribe/success',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsletterSubscribeErrorRoute =
  NewsletterSubscribeErrorRouteImport.update({
    id: '/newsletter/subscribe/error',
    path: '/newsletter/subscribe/error',
    getParentRoute: () => rootRouteImport,
  } as any)
const MainQuestsGameIdMapIdRoute = MainQuestsGameIdMapIdRouteImport.update({
  id: '/$gameId/$mapId',
  path: '/$gameId/$mapId',
  getParentRoute: () => MainQuestsRoute,
} as any)
const ApiNewsletterUnsubscribeRoute =
  ApiNewsletterUnsubscribeRouteImport.update({
    id: '/api/newsletter/unsubscribe',
    path: '/api/newsletter/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNewsletterSubscribeRoute = ApiNewsletterSubscribeRouteImport.update({
  id: '/api/newsletter/subscribe',
  path: '/api/newsletter/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SideQuestsGameIdMapIdQuestIdRoute =
  SideQuestsGameIdMapIdQuestIdRouteImport.update({
    id: '/$gameId/$mapId/$questId',
    path: '/$gameId/$mapId/$questId',
    getParentRoute: () => SideQuestsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bestiary': typeof BestiaryRouteWithChildren
  '/main-quests': typeof MainQuestsRouteWithChildren
  '/maps': typeof MapsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/relics': typeof RelicsRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/side-quests': typeof SideQuestsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bestiary/$zombieId': typeof BestiaryZombieIdRoute
  '/maps/$mapId': typeof MapsMapIdRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRouteWithChildren
  '/bestiary/': typeof BestiaryIndexRoute
  '/main-quests/': typeof MainQuestsIndexRoute
  '/maps/': typeof MapsIndexRoute
  '/relics/': typeof RelicsIndexRoute
  '/side-quests/': typeof SideQuestsIndexRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/api/newsletter/unsubscribe': typeof ApiNewsletterUnsubscribeRoute
  '/main-quests/$gameId/$mapId': typeof MainQuestsGameIdMapIdRoute
  '/newsletter/subscribe/error': typeof NewsletterSubscribeErrorRoute
  '/newsletter/subscribe/success': typeof NewsletterSubscribeSuccessRoute
  '/newsletter/unsubscribe/error': typeof NewsletterUnsubscribeErrorRoute
  '/newsletter/unsubscribe/success': typeof NewsletterUnsubscribeSuccessRoute
  '/relics/$gameId/$relicId': typeof RelicsGameIdRelicIdRoute
  '/newsletter/unsubscribe/': typeof NewsletterUnsubscribeIndexRoute
  '/side-quests/$gameId/$mapId/$questId': typeof SideQuestsGameIdMapIdQuestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bestiary/$zombieId': typeof BestiaryZombieIdRoute
  '/maps/$mapId': typeof MapsMapIdRoute
  '/bestiary': typeof BestiaryIndexRoute
  '/main-quests': typeof MainQuestsIndexRoute
  '/maps': typeof MapsIndexRoute
  '/relics': typeof RelicsIndexRoute
  '/side-quests': typeof SideQuestsIndexRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/api/newsletter/unsubscribe': typeof ApiNewsletterUnsubscribeRoute
  '/main-quests/$gameId/$mapId': typeof MainQuestsGameIdMapIdRoute
  '/newsletter/subscribe/error': typeof NewsletterSubscribeErrorRoute
  '/newsletter/subscribe/success': typeof NewsletterSubscribeSuccessRoute
  '/newsletter/unsubscribe/error': typeof NewsletterUnsubscribeErrorRoute
  '/newsletter/unsubscribe/success': typeof NewsletterUnsubscribeSuccessRoute
  '/relics/$gameId/$relicId': typeof RelicsGameIdRelicIdRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeIndexRoute
  '/side-quests/$gameId/$mapId/$questId': typeof SideQuestsGameIdMapIdQuestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bestiary': typeof BestiaryRouteWithChildren
  '/main-quests': typeof MainQuestsRouteWithChildren
  '/maps': typeof MapsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/relics': typeof RelicsRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/side-quests': typeof SideQuestsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bestiary/$zombieId': typeof BestiaryZombieIdRoute
  '/maps/$mapId': typeof MapsMapIdRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRouteWithChildren
  '/bestiary/': typeof BestiaryIndexRoute
  '/main-quests/': typeof MainQuestsIndexRoute
  '/maps/': typeof MapsIndexRoute
  '/relics/': typeof RelicsIndexRoute
  '/side-quests/': typeof SideQuestsIndexRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/api/newsletter/unsubscribe': typeof ApiNewsletterUnsubscribeRoute
  '/main-quests/$gameId/$mapId': typeof MainQuestsGameIdMapIdRoute
  '/newsletter/subscribe/error': typeof NewsletterSubscribeErrorRoute
  '/newsletter/subscribe/success': typeof NewsletterSubscribeSuccessRoute
  '/newsletter/unsubscribe/error': typeof NewsletterUnsubscribeErrorRoute
  '/newsletter/unsubscribe/success': typeof NewsletterUnsubscribeSuccessRoute
  '/relics/$gameId/$relicId': typeof RelicsGameIdRelicIdRoute
  '/newsletter/unsubscribe/': typeof NewsletterUnsubscribeIndexRoute
  '/side-quests/$gameId/$mapId/$questId': typeof SideQuestsGameIdMapIdQuestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bestiary'
    | '/main-quests'
    | '/maps'
    | '/privacy-policy'
    | '/relics'
    | '/robots.txt'
    | '/side-quests'
    | '/sitemap.xml'
    | '/bestiary/$zombieId'
    | '/maps/$mapId'
    | '/newsletter/unsubscribe'
    | '/bestiary/'
    | '/main-quests/'
    | '/maps/'
    | '/relics/'
    | '/side-quests/'
    | '/api/newsletter/subscribe'
    | '/api/newsletter/unsubscribe'
    | '/main-quests/$gameId/$mapId'
    | '/newsletter/subscribe/error'
    | '/newsletter/subscribe/success'
    | '/newsletter/unsubscribe/error'
    | '/newsletter/unsubscribe/success'
    | '/relics/$gameId/$relicId'
    | '/newsletter/unsubscribe/'
    | '/side-quests/$gameId/$mapId/$questId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/bestiary/$zombieId'
    | '/maps/$mapId'
    | '/bestiary'
    | '/main-quests'
    | '/maps'
    | '/relics'
    | '/side-quests'
    | '/api/newsletter/subscribe'
    | '/api/newsletter/unsubscribe'
    | '/main-quests/$gameId/$mapId'
    | '/newsletter/subscribe/error'
    | '/newsletter/subscribe/success'
    | '/newsletter/unsubscribe/error'
    | '/newsletter/unsubscribe/success'
    | '/relics/$gameId/$relicId'
    | '/newsletter/unsubscribe'
    | '/side-quests/$gameId/$mapId/$questId'
  id:
    | '__root__'
    | '/'
    | '/bestiary'
    | '/main-quests'
    | '/maps'
    | '/privacy-policy'
    | '/relics'
    | '/robots.txt'
    | '/side-quests'
    | '/sitemap.xml'
    | '/bestiary/$zombieId'
    | '/maps/$mapId'
    | '/newsletter/unsubscribe'
    | '/bestiary/'
    | '/main-quests/'
    | '/maps/'
    | '/relics/'
    | '/side-quests/'
    | '/api/newsletter/subscribe'
    | '/api/newsletter/unsubscribe'
    | '/main-quests/$gameId/$mapId'
    | '/newsletter/subscribe/error'
    | '/newsletter/subscribe/success'
    | '/newsletter/unsubscribe/error'
    | '/newsletter/unsubscribe/success'
    | '/relics/$gameId/$relicId'
    | '/newsletter/unsubscribe/'
    | '/side-quests/$gameId/$mapId/$questId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BestiaryRoute: typeof BestiaryRouteWithChildren
  MainQuestsRoute: typeof MainQuestsRouteWithChildren
  MapsRoute: typeof MapsRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RelicsRoute: typeof RelicsRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SideQuestsRoute: typeof SideQuestsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  NewsletterUnsubscribeRoute: typeof NewsletterUnsubscribeRouteWithChildren
  ApiNewsletterSubscribeRoute: typeof ApiNewsletterSubscribeRoute
  ApiNewsletterUnsubscribeRoute: typeof ApiNewsletterUnsubscribeRoute
  NewsletterSubscribeErrorRoute: typeof NewsletterSubscribeErrorRoute
  NewsletterSubscribeSuccessRoute: typeof NewsletterSubscribeSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/side-quests': {
      id: '/side-quests'
      path: '/side-quests'
      fullPath: '/side-quests'
      preLoaderRoute: typeof SideQuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relics': {
      id: '/relics'
      path: '/relics'
      fullPath: '/relics'
      preLoaderRoute: typeof RelicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main-quests': {
      id: '/main-quests'
      path: '/main-quests'
      fullPath: '/main-quests'
      preLoaderRoute: typeof MainQuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary': {
      id: '/bestiary'
      path: '/bestiary'
      fullPath: '/bestiary'
      preLoaderRoute: typeof BestiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/side-quests/': {
      id: '/side-quests/'
      path: '/'
      fullPath: '/side-quests/'
      preLoaderRoute: typeof SideQuestsIndexRouteImport
      parentRoute: typeof SideQuestsRoute
    }
    '/relics/': {
      id: '/relics/'
      path: '/'
      fullPath: '/relics/'
      preLoaderRoute: typeof RelicsIndexRouteImport
      parentRoute: typeof RelicsRoute
    }
    '/maps/': {
      id: '/maps/'
      path: '/'
      fullPath: '/maps/'
      preLoaderRoute: typeof MapsIndexRouteImport
      parentRoute: typeof MapsRoute
    }
    '/main-quests/': {
      id: '/main-quests/'
      path: '/'
      fullPath: '/main-quests/'
      preLoaderRoute: typeof MainQuestsIndexRouteImport
      parentRoute: typeof MainQuestsRoute
    }
    '/bestiary/': {
      id: '/bestiary/'
      path: '/'
      fullPath: '/bestiary/'
      preLoaderRoute: typeof BestiaryIndexRouteImport
      parentRoute: typeof BestiaryRoute
    }
    '/newsletter/unsubscribe': {
      id: '/newsletter/unsubscribe'
      path: '/newsletter/unsubscribe'
      fullPath: '/newsletter/unsubscribe'
      preLoaderRoute: typeof NewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/$mapId': {
      id: '/maps/$mapId'
      path: '/$mapId'
      fullPath: '/maps/$mapId'
      preLoaderRoute: typeof MapsMapIdRouteImport
      parentRoute: typeof MapsRoute
    }
    '/bestiary/$zombieId': {
      id: '/bestiary/$zombieId'
      path: '/$zombieId'
      fullPath: '/bestiary/$zombieId'
      preLoaderRoute: typeof BestiaryZombieIdRouteImport
      parentRoute: typeof BestiaryRoute
    }
    '/newsletter/unsubscribe/': {
      id: '/newsletter/unsubscribe/'
      path: '/'
      fullPath: '/newsletter/unsubscribe/'
      preLoaderRoute: typeof NewsletterUnsubscribeIndexRouteImport
      parentRoute: typeof NewsletterUnsubscribeRoute
    }
    '/relics/$gameId/$relicId': {
      id: '/relics/$gameId/$relicId'
      path: '/$gameId/$relicId'
      fullPath: '/relics/$gameId/$relicId'
      preLoaderRoute: typeof RelicsGameIdRelicIdRouteImport
      parentRoute: typeof RelicsRoute
    }
    '/newsletter/unsubscribe/success': {
      id: '/newsletter/unsubscribe/success'
      path: '/success'
      fullPath: '/newsletter/unsubscribe/success'
      preLoaderRoute: typeof NewsletterUnsubscribeSuccessRouteImport
      parentRoute: typeof NewsletterUnsubscribeRoute
    }
    '/newsletter/unsubscribe/error': {
      id: '/newsletter/unsubscribe/error'
      path: '/error'
      fullPath: '/newsletter/unsubscribe/error'
      preLoaderRoute: typeof NewsletterUnsubscribeErrorRouteImport
      parentRoute: typeof NewsletterUnsubscribeRoute
    }
    '/newsletter/subscribe/success': {
      id: '/newsletter/subscribe/success'
      path: '/newsletter/subscribe/success'
      fullPath: '/newsletter/subscribe/success'
      preLoaderRoute: typeof NewsletterSubscribeSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/subscribe/error': {
      id: '/newsletter/subscribe/error'
      path: '/newsletter/subscribe/error'
      fullPath: '/newsletter/subscribe/error'
      preLoaderRoute: typeof NewsletterSubscribeErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main-quests/$gameId/$mapId': {
      id: '/main-quests/$gameId/$mapId'
      path: '/$gameId/$mapId'
      fullPath: '/main-quests/$gameId/$mapId'
      preLoaderRoute: typeof MainQuestsGameIdMapIdRouteImport
      parentRoute: typeof MainQuestsRoute
    }
    '/api/newsletter/unsubscribe': {
      id: '/api/newsletter/unsubscribe'
      path: '/api/newsletter/unsubscribe'
      fullPath: '/api/newsletter/unsubscribe'
      preLoaderRoute: typeof ApiNewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/subscribe': {
      id: '/api/newsletter/subscribe'
      path: '/api/newsletter/subscribe'
      fullPath: '/api/newsletter/subscribe'
      preLoaderRoute: typeof ApiNewsletterSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/side-quests/$gameId/$mapId/$questId': {
      id: '/side-quests/$gameId/$mapId/$questId'
      path: '/$gameId/$mapId/$questId'
      fullPath: '/side-quests/$gameId/$mapId/$questId'
      preLoaderRoute: typeof SideQuestsGameIdMapIdQuestIdRouteImport
      parentRoute: typeof SideQuestsRoute
    }
  }
}

interface BestiaryRouteChildren {
  BestiaryZombieIdRoute: typeof BestiaryZombieIdRoute
  BestiaryIndexRoute: typeof BestiaryIndexRoute
}

const BestiaryRouteChildren: BestiaryRouteChildren = {
  BestiaryZombieIdRoute: BestiaryZombieIdRoute,
  BestiaryIndexRoute: BestiaryIndexRoute,
}

const BestiaryRouteWithChildren = BestiaryRoute._addFileChildren(
  BestiaryRouteChildren,
)

interface MainQuestsRouteChildren {
  MainQuestsIndexRoute: typeof MainQuestsIndexRoute
  MainQuestsGameIdMapIdRoute: typeof MainQuestsGameIdMapIdRoute
}

const MainQuestsRouteChildren: MainQuestsRouteChildren = {
  MainQuestsIndexRoute: MainQuestsIndexRoute,
  MainQuestsGameIdMapIdRoute: MainQuestsGameIdMapIdRoute,
}

const MainQuestsRouteWithChildren = MainQuestsRoute._addFileChildren(
  MainQuestsRouteChildren,
)

interface MapsRouteChildren {
  MapsMapIdRoute: typeof MapsMapIdRoute
  MapsIndexRoute: typeof MapsIndexRoute
}

const MapsRouteChildren: MapsRouteChildren = {
  MapsMapIdRoute: MapsMapIdRoute,
  MapsIndexRoute: MapsIndexRoute,
}

const MapsRouteWithChildren = MapsRoute._addFileChildren(MapsRouteChildren)

interface RelicsRouteChildren {
  RelicsIndexRoute: typeof RelicsIndexRoute
  RelicsGameIdRelicIdRoute: typeof RelicsGameIdRelicIdRoute
}

const RelicsRouteChildren: RelicsRouteChildren = {
  RelicsIndexRoute: RelicsIndexRoute,
  RelicsGameIdRelicIdRoute: RelicsGameIdRelicIdRoute,
}

const RelicsRouteWithChildren =
  RelicsRoute._addFileChildren(RelicsRouteChildren)

interface SideQuestsRouteChildren {
  SideQuestsIndexRoute: typeof SideQuestsIndexRoute
  SideQuestsGameIdMapIdQuestIdRoute: typeof SideQuestsGameIdMapIdQuestIdRoute
}

const SideQuestsRouteChildren: SideQuestsRouteChildren = {
  SideQuestsIndexRoute: SideQuestsIndexRoute,
  SideQuestsGameIdMapIdQuestIdRoute: SideQuestsGameIdMapIdQuestIdRoute,
}

const SideQuestsRouteWithChildren = SideQuestsRoute._addFileChildren(
  SideQuestsRouteChildren,
)

interface NewsletterUnsubscribeRouteChildren {
  NewsletterUnsubscribeErrorRoute: typeof NewsletterUnsubscribeErrorRoute
  NewsletterUnsubscribeSuccessRoute: typeof NewsletterUnsubscribeSuccessRoute
  NewsletterUnsubscribeIndexRoute: typeof NewsletterUnsubscribeIndexRoute
}

const NewsletterUnsubscribeRouteChildren: NewsletterUnsubscribeRouteChildren = {
  NewsletterUnsubscribeErrorRoute: NewsletterUnsubscribeErrorRoute,
  NewsletterUnsubscribeSuccessRoute: NewsletterUnsubscribeSuccessRoute,
  NewsletterUnsubscribeIndexRoute: NewsletterUnsubscribeIndexRoute,
}

const NewsletterUnsubscribeRouteWithChildren =
  NewsletterUnsubscribeRoute._addFileChildren(
    NewsletterUnsubscribeRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BestiaryRoute: BestiaryRouteWithChildren,
  MainQuestsRoute: MainQuestsRouteWithChildren,
  MapsRoute: MapsRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RelicsRoute: RelicsRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SideQuestsRoute: SideQuestsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  NewsletterUnsubscribeRoute: NewsletterUnsubscribeRouteWithChildren,
  ApiNewsletterSubscribeRoute: ApiNewsletterSubscribeRoute,
  ApiNewsletterUnsubscribeRoute: ApiNewsletterUnsubscribeRoute,
  NewsletterSubscribeErrorRoute: NewsletterSubscribeErrorRoute,
  NewsletterSubscribeSuccessRoute: NewsletterSubscribeSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
